export {
  SOCIAL_CHANNELS,
  SOCIAL_UTM_MEDIUM,
  CHEF_GRINGO_CANONICAL_ORIGIN,
  CHEF_GRINGO_OWNED_HOSTS,
  assertSocialChannel,
  isSocialChannel,
  type SocialChannel,
} from "./channels.ts";
export {
  SOCIAL_GROWTH_ID_KINDS,
  assertSocialGrowthId,
  isSocialGrowthId,
  normalizeSocialSlug,
  parseSocialGrowthId,
  socialGrowthId,
  type SocialGrowthIdKind,
} from "./ids.ts";
export {
  mintSocialDestinationUrl,
  parseChefGringoDestination,
  RESERVED_UTM_KEYS,
  type MintedSocialDestination,
  type MintSocialDestinationInput,
} from "./utm.ts";
export {
  SOCIAL_COMMERCIAL_POSTURES,
  assertNoEconomicsRankingFields,
  assertPostureMatchesLinkKind,
  assertSocialCommercialPosture,
  commercialLinkKindForPosture,
  isSocialCommercialPosture,
  socialPackageMayMonetize,
  type SocialCommercialPosture,
} from "./commercial.ts";
export {
  SOCIAL_EVIDENCE_KINDS,
  assertSocialEvidenceRef,
  claimMaySupportApproval,
  isSocialEvidenceKind,
  type ReferencedEvidenceState,
  type SocialEvidenceKind,
  type SocialEvidenceRef,
} from "./claims.ts";
export {
  CLAIM_DECOMPOSITION_VERSION,
  CLAIM_PROPOSAL_KINDS,
  CLAIM_PROPOSAL_STATUSES,
  claimHasAttachedEvidence,
  claimProposalKey,
  decomposePackageToClaimProposals,
  isClaimProposalKind,
  isClaimProposalStatus,
  normalizeClaimProposalText,
  packageDecompositionFingerprint,
  type ClaimProposalDraft,
  type ClaimProposalKind,
  type ClaimProposalStatus,
  type PersistedClaimProposal,
} from "./claim-decomposition.ts";
export {
  INVESTIGATION_REFINEMENT_VERSION,
  MAX_INVESTIGATION_ITEMS,
  MAX_REFINEMENT_DEPTH,
  materialInvestigationItems,
  refineInvestigationPlan,
  type InvestigationItem,
  type InvestigationPlanDraft,
} from "./investigation-refinement.ts";
export {
  AUTONOMY_PERMISSION_MATRIX,
  FORBIDDEN_OPERATOR_ACTIONS,
  MAX_OPERATOR_STEPS,
  OPERATOR_VERSION,
  assertOperatorActionAllowed,
  buildOperatorSummary,
  classifyOperatorState,
  isInvestigationReviewAcknowledgment,
  operatorRequestForPrimaryAction,
  operatorViewFromRecords,
  primaryOperatorAction,
  type OperatorState,
  type OperatorSummary,
} from "./operator-state.ts";
export {
  SOCIAL_APPROVAL_DECISIONS,
  SOCIAL_APPROVAL_SUBJECTS,
  SOCIAL_ASSET_TYPES,
  SOCIAL_AUDIENCES,
  SOCIAL_GROWTH_STEP,
  SOCIAL_OPPORTUNITY_STATUSES,
  SOCIAL_PACKAGE_STATUSES,
  SOCIAL_PUBLISH_AVAILABLE,
  isSocialApprovalDecision,
  isSocialAssetType,
  isSocialAudience,
  isSocialOpportunityStatus,
  isSocialPackageStatus,
  type SocialApproval,
  type SocialApprovalDecision,
  type SocialApprovalSubjectKind,
  type SocialAssetType,
  type SocialAudience,
  type SocialChannelVariant,
  type SocialContentAsset,
  type SocialContentOpportunity,
  type SocialContentPackage,
  type SocialDestinationUrl,
  type SocialOpportunityStatus,
  type SocialPackageClaim,
  type SocialPackageStatus,
  type SocialPerformanceSnapshot,
  type SocialPublication,
} from "./types.ts";
export {
  approvalIsValidAuthority,
  assertActorEmail,
  assertApprovalSubject,
  assertPublishUnavailable,
  canPublishNow,
  createApprovalRecord,
  hasValidSocialApproval,
  hasValidSocialPublicationAuthority,
  publicationIsAuthorized,
} from "./approvals.ts";
export {
  SOCIAL_PLATFORM_HOSTS,
  canonicalizePlatformPostIdentity,
  canonicalizePlatformPostUrl,
  parsePlatformPostUrl,
  type ParsedPlatformPostUrl,
} from "./platform-urls.ts";
export {
  SOCIAL_PUBLICATION_MODE,
  SOCIAL_PUBLICATION_STATUSES,
  assertManualPublicationMode,
  assertPublishedAt,
  createManualPublicationDraft,
  createReservedPublicationDraft,
  mintPublicationTrackedUrl,
  normalizePlatformPostId,
  socialPublicationAttribution,
  socialPublicationId,
  type SocialPublicationAttribution,
  type SocialPublicationStatus,
} from "./publications.ts";
export {
  SOCIAL_EVIDENCE_PREFERRED_SOURCE_TYPES,
  SOCIAL_EVIDENCE_REQUEST_STATUSES,
  assertResolvedEvidenceRef,
  candidateStatusFromCorpus,
  createEvidenceRequestDraft,
  evidenceRequestCannotSatisfyGate,
  isSocialEvidencePreferredSourceType,
  isSocialEvidenceRequestStatus,
  requestMayResolveFromCorpus,
  socialEvidenceRequestId,
  type SocialEvidencePreferredSourceType,
  type SocialEvidenceRequest,
  type SocialEvidenceRequestStatus,
} from "./evidence-requests.ts";
export {
  EVIDENCE_POLICY,
  EVIDENCE_POLICY_CLASSES,
  FORBIDDEN_EVIDENCE_ECONOMICS_KEYS,
  authorityClassFromSourceMetadata,
  deriveClaimPolicyClass,
  type EvidenceAuthorityClass,
  type EvidencePolicyClass,
} from "./evidence-policy.ts";
export {
  EVIDENCE_SUFFICIENCY_STATES,
  assessClaimSufficiency,
  assessEvidenceRequestGap,
  buildDecisionDna,
  buildEvidenceGapRadar,
  buildResearchPlan,
  classifyAutonomyReadiness,
  hasIntelligenceReadyApprovalAuthority,
  independenceCluster,
  recordIsAcceptedSupport,
  type ClaimSufficiencyAssessment,
  type DecisionDna,
  type EvidenceGapRadar,
  type EvidenceResearchPlan,
  type EvidenceSnapshot,
  type EvidenceSufficiencyState,
  type PackageEvidenceIntelligence,
  type AutonomyReadinessState,
} from "./evidence-intelligence.ts";
export {
  BOUNDED_CANDIDATE_DISCOVERY_ENABLED,
  BRAVE_WEB_SEARCH_ENDPOINT,
  CANDIDATE_DISCOVERY_PROVIDER_ID,
  LIVE_CANDIDATE_DISCOVERY_PROVIDER_ID,
  candidateDiscoveryCapability,
  liveCandidateDiscoveryAvailable,
  readLiveDiscoveryConfig,
} from "./candidate-discovery-capability.ts";
export {
  buildBoundedResearchQueries,
  buildBoundedResearchQueryPlans,
  buildExecutableResearchPlan,
  executablePlanFromClaimAssessment,
  expandExecutableResearchPlan,
  type ExecutableResearchPlan,
  type ResearchRiskClass,
} from "./research-planner.ts";
export {
  AUTHORITY_PATHS,
  EVIDENCE_GAP_RESEARCH_VERSION,
  POLICY_ADVANCEMENTS,
  buildAuthoritativeQueryPlans,
  buildEvidenceGapFeedback,
  buildGapAwareQueries,
  candidateConsumesAssessedCapacity,
  classifyPolicyAdvancement,
  evaluatePreRetrievalExclusion,
  exclusionSiteTerms,
  queryPlansAreDiverse,
  type AuthorityPath,
  type EvidenceGapFeedback,
  type PolicyAdvancement,
  type ResearchQueryPlan,
} from "./evidence-gap-research.ts";
export {
  classifySearchSurface,
  compareSearchSurfaces,
  searchSurfaceDiscoveryScore,
} from "./authoritative-source-targeting.ts";
export {
  EDITORIAL_DOMAIN_DEMOTE_THRESHOLD,
  RESEARCH_MEMORY_RETRY_HORIZON_MS,
  RESEARCH_MEMORY_VERSION,
  buildResearchMemory,
  editorialDomainsToDemote,
  emptyResearchMemory,
  evaluateMemorySkip,
  memoryUrlsToSkipBeforeRetrieval,
  runMatchesResearchMemoryScope,
  summarizeResearchMemory,
  type MemoryState,
  type ResearchMemory,
} from "./research-memory.ts";
export { compactResearchQueryTerms } from "../../lib/research/plan.ts";
export {
  LIVE_DOCUMENT_FETCH_CONCURRENCY,
  describeLiveEmptyReason,
  diagnosticsOmitSecrets,
  type LiveEmptyReason,
  type LiveRetrievalDiagnostics,
} from "../../lib/research/live-retrieval-diagnostics.ts";
export {
  assessDiscoveredHit,
  classifyCandidateRelationship,
  executeBoundedCandidateDiscovery,
  extractTraceableExcerpt,
  rankCandidateAssessments,
  resolveCandidateDiscoveryProvider,
  wouldSatisfyPolicyIfAccepted,
  type CandidateAssessment,
  type CandidateRelationship,
  type ResearchRunResult,
} from "./candidate-discovery.ts";
export {
  SOCIAL_ATTRIBUTION_STATES,
  SOCIAL_PERFORMANCE_WINDOWS,
  aggregateSocialPerformance,
  classifySocialEventAttribution,
  emptySocialPublicationMetrics,
  eventOccursInWindow,
  isSocialPerformanceWindow,
  resolveSocialPerformanceWindow,
  type SocialAttributionState,
  type SocialPerformanceEvent,
  type SocialPerformanceReport,
  type SocialPerformanceWindow,
  type SocialPublicationMetrics,
} from "./performance.ts";
export {
  CONTENT_CTA_TYPES,
  CONTENT_FORMATS,
  CONTENT_INTELLIGENCE_VERSION,
  COMMERCIAL_ROUTE_TYPES,
  buildContentIntelligence,
  buildContentIntelligenceBrief,
  planCommercialRoute,
  scoreContentOpportunity,
  selectContentFormats,
  verifiedFactsFromIntelligence,
  type CommercialRoutePlan,
  type CommercialRouteType,
  type ContentAttributionPlan,
  type ContentCtaType,
  type ContentFormat,
  type ContentFormatPlan,
  type ContentIntelligenceBrief,
  type ContentIntelligenceWorkspace,
  type ContentOpportunityScore,
} from "./content-intelligence.ts";
export {
  draftContentFormats,
  everyFactualSegmentIsTraced,
  type ContentDraft,
  type DraftSegment,
} from "./content-drafts.ts";
export {
  DRAFT_CLAIM_FIREWALL_VERSION,
  DRAFT_FIREWALL_STATUSES,
  DRAFT_STATEMENT_CLASSES,
  applyDraftClaimFirewall,
  asResearchQuestion,
  classifyDraftStatement,
  everyRemainingAssertiveStatementIsAuthorized,
  hedgesDoNotAuthorize,
  mapStatementToVerifiedFacts,
  splitDraftStatements,
  statementBroadensClaim,
  transformUnsupportedStatement,
  type DraftClaimFirewallResult,
  type DraftFirewallStatus,
  type DraftStatementClass,
  type DraftStatementTrace,
} from "./draft-claim-firewall.ts";
export {
  GROWTH_LEARNING_ACTIONS,
  buildGrowthLearningSignal,
  type GrowthLearningAction,
  type GrowthLearningSignal,
} from "./growth-learning.ts";
