export {
  SOCIAL_CHANNELS,
  SOCIAL_UTM_MEDIUM,
  CHEF_GRINGO_CANONICAL_ORIGIN,
  CHEF_GRINGO_OWNED_HOSTS,
  assertSocialChannel,
  isSocialChannel,
  type SocialChannel,
} from "./channels.ts";
export {
  SOCIAL_GROWTH_ID_KINDS,
  assertSocialGrowthId,
  isSocialGrowthId,
  normalizeSocialSlug,
  parseSocialGrowthId,
  socialGrowthId,
  type SocialGrowthIdKind,
} from "./ids.ts";
export {
  mintSocialDestinationUrl,
  parseChefGringoDestination,
  RESERVED_UTM_KEYS,
  type MintedSocialDestination,
  type MintSocialDestinationInput,
} from "./utm.ts";
export {
  SOCIAL_COMMERCIAL_POSTURES,
  assertNoEconomicsRankingFields,
  assertPostureMatchesLinkKind,
  assertSocialCommercialPosture,
  commercialLinkKindForPosture,
  isSocialCommercialPosture,
  socialPackageMayMonetize,
  type SocialCommercialPosture,
} from "./commercial.ts";
export {
  SOCIAL_EVIDENCE_KINDS,
  assertSocialEvidenceRef,
  claimMaySupportApproval,
  isSocialEvidenceKind,
  type ReferencedEvidenceState,
  type SocialEvidenceKind,
  type SocialEvidenceRef,
} from "./claims.ts";
export {
  SOCIAL_APPROVAL_DECISIONS,
  SOCIAL_APPROVAL_SUBJECTS,
  SOCIAL_ASSET_TYPES,
  SOCIAL_AUDIENCES,
  SOCIAL_GROWTH_STEP,
  SOCIAL_OPPORTUNITY_STATUSES,
  SOCIAL_PACKAGE_STATUSES,
  SOCIAL_PUBLISH_AVAILABLE,
  isSocialApprovalDecision,
  isSocialAssetType,
  isSocialAudience,
  isSocialOpportunityStatus,
  isSocialPackageStatus,
  type SocialApproval,
  type SocialApprovalDecision,
  type SocialApprovalSubjectKind,
  type SocialAssetType,
  type SocialAudience,
  type SocialChannelVariant,
  type SocialContentAsset,
  type SocialContentOpportunity,
  type SocialContentPackage,
  type SocialDestinationUrl,
  type SocialOpportunityStatus,
  type SocialPackageClaim,
  type SocialPackageStatus,
  type SocialPerformanceSnapshot,
  type SocialPublication,
} from "./types.ts";
export {
  approvalIsValidAuthority,
  assertActorEmail,
  assertApprovalSubject,
  assertPublishUnavailable,
  canPublishNow,
  createApprovalRecord,
  hasValidSocialApproval,
  hasValidSocialPublicationAuthority,
  publicationIsAuthorized,
} from "./approvals.ts";
export {
  SOCIAL_PLATFORM_HOSTS,
  canonicalizePlatformPostIdentity,
  canonicalizePlatformPostUrl,
  parsePlatformPostUrl,
  type ParsedPlatformPostUrl,
} from "./platform-urls.ts";
export {
  SOCIAL_PUBLICATION_MODE,
  SOCIAL_PUBLICATION_STATUSES,
  assertManualPublicationMode,
  assertPublishedAt,
  createManualPublicationDraft,
  createReservedPublicationDraft,
  mintPublicationTrackedUrl,
  normalizePlatformPostId,
  socialPublicationAttribution,
  socialPublicationId,
  type SocialPublicationAttribution,
  type SocialPublicationStatus,
} from "./publications.ts";
export {
  SOCIAL_ATTRIBUTION_STATES,
  SOCIAL_PERFORMANCE_WINDOWS,
  aggregateSocialPerformance,
  classifySocialEventAttribution,
  emptySocialPublicationMetrics,
  eventOccursInWindow,
  isSocialPerformanceWindow,
  resolveSocialPerformanceWindow,
  type SocialAttributionState,
  type SocialPerformanceEvent,
  type SocialPerformanceReport,
  type SocialPerformanceWindow,
  type SocialPublicationMetrics,
} from "./performance.ts";
