import assert from "node:assert/strict";
import test from "node:test";
import {applyMigrations,SqliteD1Adapter} from "./helpers/sqlite-d1.mjs";
import {approveOutboxEntry,createOutboxEntry,getGrowthControls,setGrowthControl,transitionOutboxEntry} from "../db/growth-os-repository.ts";

async function database(){const db=new SqliteD1Adapter();await applyMigrations(db);return db;}
function seedWorkspace(db,{posture="none",partnerId=null}={}){
  db.database.prepare("INSERT INTO social_content_opportunities (id,slug,problem,audience,usefulness_test,partner_opportunity_id,status) VALUES (?,?,?,?,?,?,?)").run("sgo:opportunity:growth-os-test","growth-os-test","Test safe publishing.","independent_operator","Must fail closed.",partnerId,"selected");
  db.database.prepare("INSERT INTO social_content_packages (id,slug,opportunity_id,thesis,usefulness_test,commercial_posture,status) VALUES (?,?,?,?,?,?,?)").run("sgo:package:growth-os-test","growth-os-test","sgo:opportunity:growth-os-test","Safe test.","No unsafe dispatch.",posture,"approved");
  db.database.prepare("INSERT INTO social_channel_variants (id,package_id,channel,copy,asset_ids,destination_url_id) VALUES (?,?,?,?,?,?)").run("sgo:variant:growth-os-test","sgo:package:growth-os-test","instagram","Approved organic caption.","[]","sgo:destination:growth-os-test");
  db.database.prepare("INSERT INTO social_destination_urls (id,package_id,variant_id,channel,path,href) VALUES (?,?,?,?,?,?)").run("sgo:destination:growth-os-test","sgo:package:growth-os-test","sgo:variant:growth-os-test","instagram","/learn","https://chefgringo.com/learn?utm_source=instagram");
}
const input={packageId:"sgo:package:growth-os-test",variantId:"sgo:variant:growth-os-test",destinationUrlId:"sgo:destination:growth-os-test",channel:"instagram",targetAccount:"chefgringo",trackedHref:"https://chefgringo.com/learn?utm_source=instagram",createdBy:"admin@example.com"};

test("Growth OS controls default closed and paid publishing cannot be enabled",async()=>{const db=await database();try{const controls=await getGrowthControls(db);for(const control of controls)assert.equal(control.enabled,false,control.scope);await assert.rejects(()=>setGrowthControl(db,{scope:"paid_publishing",enabled:true,reason:"should fail",actorEmail:"admin@example.com"}),/cannot be enabled/)}finally{db.close()}});

test("outbox creation is idempotent and cannot advance without durable approval",async()=>{const db=await database();try{seedWorkspace(db);const first=await createOutboxEntry(db,input);const duplicate=await createOutboxEntry(db,input);assert.equal(first.id,duplicate.id);assert.equal(first.state,"awaiting_approval");await assert.rejects(()=>approveOutboxEntry(db,first.id,"admin@example.com"),/durable package or variant approval/);db.database.prepare("INSERT INTO social_approvals (id,subject_kind,subject_id,decision,actor_email,reason,occurred_at) VALUES (?,?,?,?,?,?,?)").run("sgo:approval:growth-os-test","package",input.packageId,"approved","reviewer@example.com","Reviewed.",new Date().toISOString());const approved=await approveOutboxEntry(db,first.id,"admin@example.com");assert.equal(approved.state,"approved_waiting");assert.equal(approved.approvalId,"sgo:approval:growth-os-test")}finally{db.close()}});

test("approved outbox still cannot dispatch while any kill switch is closed",async()=>{const db=await database();try{seedWorkspace(db);db.database.prepare("INSERT INTO social_approvals (id,subject_kind,subject_id,decision,actor_email,reason,occurred_at) VALUES (?,?,?,?,?,?,?)").run("sgo:approval:growth-os-test","package",input.packageId,"approved","reviewer@example.com","Reviewed.",new Date().toISOString());const job=await createOutboxEntry(db,input);await approveOutboxEntry(db,job.id,"admin@example.com");await assert.rejects(()=>transitionOutboxEntry(db,{id:job.id,toState:"sending",actorEmail:"admin@example.com"}),/kill switch/);for(const scope of ["global_outbound","organic_publishing","dispatcher","channel:instagram"])await setGrowthControl(db,{scope,enabled:true,reason:"isolated test only",actorEmail:"admin@example.com"});const sending=await transitionOutboxEntry(db,{id:job.id,toState:"sending",actorEmail:"admin@example.com"});assert.equal(sending.state,"sending");assert.equal((await getGrowthControls(db)).find(row=>row.scope==="paid_publishing").enabled,false)}finally{db.close()}});

test("paid jobs are rejected before persistence",async()=>{const db=await database();try{seedWorkspace(db);await assert.rejects(()=>createOutboxEntry(db,{...input,publicationKind:"paid"}),/prohibited/);assert.equal(db.database.prepare("SELECT COUNT(*) AS count FROM publication_outbox").get().count,0)}finally{db.close()}});
