import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import test from "node:test";
import {syntheticPartnerOpportunities,emptyFounderMetrics} from "../app/growth/fixtures.ts";import {commercialOpportunityScore,customerValueScore,expectedCommercialValue} from "../app/growth/scoring.ts";import {COMMERCIAL_LANES,GROWTH_CAPABILITIES} from "../app/growth/types.ts";
const customer={operatorFit:90,totalCost:80,quality:85,support:82,warranty:79,switchingCost:76,contractBurden:74,reliability:88,evidence:91,expectedOperatorValue:89};
test("Growth and all revenue Marketplace lanes are provider neutral",()=>{assert.equal(GROWTH_CAPABILITIES.length,19);assert.deepEqual(COMMERCIAL_LANES,["equipment_supplies","factory_direct","pos_payments","software","services","business_capital","growth_customer_acquisition"])});
test("Customer Value and Commercial Opportunity remain structurally isolated",()=>{const editorial=customerValueScore(customer);assert.equal(editorial,customerValueScore({...customer}));assert.equal(commercialOpportunityScore({payout:100,recurringRevenue:100,revenueShare:100,expectedConversion:100,approvalProbability:100,attributionQuality:100,payoutTiming:100,reversalRisk:100,expectedLifetimeRevenue:100}),100);assert.equal(customerValueScore(customer),editorial)});
test("unknown partner economics remain unknown and expected value fails closed",()=>{for(const item of syntheticPartnerOpportunities)assert.ok(Object.values(item.economics).every(value=>value===null));assert.equal(expectedCommercialValue({payoutCents:null,conversionProbability:null,approvalProbability:null,retentionMultiplier:null,acquisitionCostCents:null}),null)});
test("fixtures contain no fake payouts, advertising performance, or founder metrics",()=>{assert.ok(Object.values(emptyFounderMetrics).every(value=>value===null));assert.doesNotMatch(JSON.stringify(syntheticPartnerOpportunities),/\$[0-9]|ROAS [0-9]|conversion rate/i)});
test("Partner Hunt remains server-authorized and private",async()=>{const source=await readFile(new URL("../app/admin/marketplace/partners/page.tsx",import.meta.url),"utf8");assert.match(source,/requireMarketplaceAdministrator/);assert.match(source,/robots:\{index:false,follow:false\}/);assert.match(source,/local in-memory workflow/)});
test("homepage keeps Growth human, reachable, and free of performance claims",async()=>{const source=await readFile(new URL("../app/page.tsx",import.meta.url),"utf8");assert.match(source,/What are you[\s\S]*working on/);assert.match(source,/operating, or growth problem/);assert.match(source,/id="grow"/);assert.doesNotMatch(source,/guaranteed leads|live ROAS|automated campaigns/i)});
