import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import test from "node:test";import {marketplaceCatalog} from "../app/marketplace/catalog.ts";import {marketplaceComparisons,problemMappings,validateProblemGraph} from "../app/marketplace/problem-graph.ts";import {merchandisingLabel,productCardViewModel} from "../app/marketplace/view-models.ts";
test("Wave 1 contains exactly 100 real non-synthetic product records",()=>{assert.equal(marketplaceCatalog.products.length,100);assert.equal(marketplaceCatalog.products.some(product=>/synthetic|example\.invalid/i.test(JSON.stringify(product))),false);for(const product of marketplaceCatalog.products){assert.equal(product.status,"published");assert.match(product.evidence[0].url,/^https:\/\//);assert.ok(product.evidence[0].checked);assert.ok(product.image.provenance)}});
test("canonical records and unknown fields survive a storage-neutral JSON round trip",()=>{const snapshot=JSON.stringify(marketplaceCatalog.products);const reloaded=JSON.parse(snapshot);assert.deepEqual(reloaded,marketplaceCatalog.products);assert.equal(reloaded.find(product=>product.id==="true-t-49-hc").price.context,"Manufacturer quote required; delivered and installed cost is not published");assert.equal(new Set(reloaded.map(product=>product.id)).size,100)});
test("new products retain honest price, image, and category-specific unknowns",()=>{const newProducts=marketplaceCatalog.products.filter(product=>product.evidence[0].checked==="2026-08-13");assert.equal(newProducts.length,70);for(const product of newProducts){assert.match(product.price.context,/must be checked|quote required/i);const media=productCardViewModel(product).media;assert.equal(media.url,null);assert.equal(media.rights,"reference_only");assert.match(product.unresolvedQuestions.join(" "),/delivered cost/)}const knife=newProducts.find(product=>product.id==="victorinox-fibrox-8");assert.ok(knife);assert.equal("electrical" in knife.specs,false);const controller=newProducts.find(product=>product.id==="ranco-etc-111000");assert.match(controller.specs.compatibility,/verified/)});
test("commercial status cannot alter ranking and unaffiliated records remain eligible",()=>{const product=structuredClone(marketplaceCatalog.products.find(item=>item.id==="true-t-49-hc"));const before=merchandisingLabel(product);product.affiliate={program:"Hypothetical program",status:"available",commission:null,cookieWindow:null,lastChecked:"2026-08-13"};assert.equal(merchandisingLabel(product),before);assert.equal(product.scores.affiliateCommission,undefined);assert.ok(marketplaceCatalog.products.some(item=>item.affiliate.status==="unavailable"&&item.scores.workflowFit>=75))});
test("problem graph and comparisons map only canonical products",()=>{assert.equal(validateProblemGraph().length,0);assert.equal(problemMappings.length,5);assert.equal(marketplaceComparisons.length,3);for(const mapping of problemMappings){assert.ok(mapping.routes.length);assert.ok(mapping.unknowns.length);assert.ok(mapping.productIds.length)}});
test("homepage uses real candidates and removes public synthetic demo surfaces",async()=>{const [page,intake]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/components/HomepageIntake.tsx",import.meta.url),"utf8")]);assert.match(page,/True T-49-HC/);assert.match(page,/Turbo Air M3R47-2-N/);assert.match(page,/Explore the platform/);assert.doesNotMatch(page+intake,/Load synthetic case|Problem proof · Existing synthetic/)});
test("bounded publication review records source, price, specification, and image-rights state",()=>{const reviewed=marketplaceCatalog.products.filter(product=>product.publication);assert.equal(reviewed.length,25);assert.equal(reviewed.filter(product=>product.publication.status==="publication_ready").length,22);assert.equal(reviewed.filter(product=>product.publication.status==="verify").length,3);for(const product of reviewed){assert.equal(product.publication.reviewedAt,"2026-08-13");assert.ok(product.publication.sourceNotes);assert.equal(product.image.licensing,"reference-only");assert.match(product.image.rightsSource,/no reuse grant/i);assert.equal(product.image.rightsChecked,"2026-08-13")}assert.match(marketplaceCatalog.products.find(product=>product.id==="fieldpiece-sm480v").evidence[0].url,/sm480v-wireless-4-port/);assert.match(marketplaceCatalog.products.find(product=>product.id==="hobart-am16").evidence[0].url,/hobart-am16-base/) });
test("homepage contextual photos carry explicit reusable-license provenance",async()=>{const images=await import("../app/home/editorial-images.ts");for(const image of Object.values(images.editorialImages)){assert.equal(image.rightsStatus,"licensed");assert.equal(image.license,"Unsplash License");assert.match(image.licenseUrl,/unsplash\.com\/license/);assert.match(image.sourceUrl,/unsplash\.com\/photos/);assert.equal(image.checked,"2026-08-13")} });
