export type WorkflowId = "better-thermometer" | "memory-care-dining" | "immersion-blender" | "coffee-setup" | "adaptive-dining" | "commercial-mixer";

export type ProductRecord = {
  id: string;
  workflowId: WorkflowId;
  manufacturer: string;
  brand: string;
  model: string;
  name: string;
  category: string;
  environments: string[];
  specs: Record<string, string>;
  evidence: { label: string; url: string; type: "manufacturer" | "merchant"; checked: string }[];
  evidenceStrength: "strong" | "moderate";
  limitations: string[];
  unresolvedQuestions: string[];
  editorial: { badge: string; bestFor: string; why: string; strengths: string[]; tradeoff: string; skipIf: string; operatorNotes: string };
  price: { context: string; checked: string };
  merchants: { name: string; url: string; availability: string; checked: string }[];
  affiliate: { program: string | null; status: "unknown" | "available" | "unavailable"; commission: null; cookieWindow: null; lastChecked: string };
  scores: { workflowFit: number; durability: number; sanitation: number; performance: number; serviceability: number; value: number; evidenceQuality: number; environmentFit: number };
  image: { referenceUrl: string; provenance: string; licensing: "reference-only" };
  status: "published";
};

const checked = "2026-08-07";

const workflows = [
  { id: "better-thermometer", title: "I need a better thermometer", context: "Food safety", summary: "Fast line checks, budget coverage, institutional familiarity, infrared screening, and monitored cooking.", knowledgeHref: "/knowledge/dishes/carbonara", knowledgeLabel: "Technique connection: temperature control in carbonara" },
  { id: "memory-care-dining", title: "I need equipment for memory care", context: "Senior living", summary: "Supportive tableware reviewed for dignity, visibility, stability, sanitation, and staff workflow—without unsupported medical claims.", knowledgeHref: "/senior-caregiver-kitchen", knowledgeLabel: "Related: senior caregiver kitchen" },
  { id: "immersion-blender", title: "I need the right immersion blender", context: "Production", summary: "Commercial tools mapped from smaller batches to sustained 80-liter production, with cleaning and service considered.", knowledgeHref: "/culinary-director-tools", knowledgeLabel: "Related: culinary director tools" },
  { id: "coffee-setup", title: "I need a reliable coffee setup", context: "Coffee", summary: "A coherent workflow: brewer, grinder, scale, and service plan instead of a pile of disconnected gadgets.", knowledgeHref: "/discover", knowledgeLabel: "Explore coffee and operations knowledge" },
  { id: "adaptive-dining", title: "I need adaptive dining equipment", context: "Accessibility", summary: "Plates, utensils, cups, and non-slip supports with explicit home, caregiver, and institutional boundaries.", knowledgeHref: "/senior-caregiver-kitchen", knowledgeLabel: "Related: supportive dining context" },
  { id: "commercial-mixer", title: "I need a commercial mixer", context: "Equipment planning", summary: "Capacity tiers from compact commercial countertop machines to serviceable 20-quart institutional workhorses.", knowledgeHref: "/tools/recipe-scaler", knowledgeLabel: "Scale the recipe before sizing the mixer" },
] as const;

type Seed = {
  id: string; workflowId: WorkflowId; manufacturer: string; model: string; category: string; badge: string;
  bestFor: string; why: string; strengths: string[]; tradeoff: string; skipIf: string; notes: string;
  price: string; source: string; sourceLabel: string; merchant: string; merchantUrl?: string;
  specs: Record<string, string>; environments: string[]; scores: ProductRecord["scores"];
  evidenceStrength?: ProductRecord["evidenceStrength"]; sourceType?: "manufacturer" | "merchant"; limitations?: string[]; affiliateProgram?: string;
};

function product(seed: Seed): ProductRecord {
  return {
    id: seed.id,
    workflowId: seed.workflowId,
    manufacturer: seed.manufacturer,
    brand: seed.manufacturer,
    model: seed.model,
    name: `${seed.manufacturer} ${seed.model}`,
    category: seed.category,
    environments: seed.environments,
    specs: seed.specs,
    evidence: [{ label: seed.sourceLabel, url: seed.source, type: seed.sourceType ?? "manufacturer", checked }],
    evidenceStrength: seed.evidenceStrength ?? "strong",
    limitations: seed.limitations ?? ["Chef Gringo has not independently bench-tested this model; manufacturer specifications are identified as such."],
    unresolvedQuestions: ["Reconfirm price, stock, exact regional SKU, and warranty with the merchant before purchase."],
    editorial: { badge: seed.badge, bestFor: seed.bestFor, why: seed.why, strengths: seed.strengths, tradeoff: seed.tradeoff, skipIf: seed.skipIf, operatorNotes: seed.notes },
    price: { context: seed.price, checked },
    merchants: [{ name: seed.merchant, url: seed.merchantUrl ?? seed.source, availability: "Check current stock and delivered price", checked }],
    affiliate: { program: seed.affiliateProgram ?? null, status: seed.affiliateProgram ? "unknown" : "unavailable", commission: null, cookieWindow: null, lastChecked: checked },
    scores: seed.scores,
    image: { referenceUrl: seed.source, provenance: `${seed.manufacturer} manufacturer product page or specification sheet`, licensing: "reference-only" },
    status: "published",
  };
}

const products: ProductRecord[] = [
  product({id:"thermoworks-thermapen-one",workflowId:"better-thermometer",manufacturer:"ThermoWorks",model:"Thermapen ONE",category:"Professional instant-read thermometer",badge:"Best overall",bestFor:"Fast, frequent line checks where seconds and sanitation matter",why:"A one-second stated response, ±0.5°F stated accuracy, IP67 body, calibration certificate, and five-year warranty form the strongest all-around working-kitchen package.",strengths:["1-second response","IP67 waterproof","NIST-traceable certificate"],tradeoff:"Costs more than basic pocket thermometers.",skipIf:"A two-to-three-second response is acceptable and budget matters more.",notes:"Color-code by station and keep a written calibration-check schedule.",price:"Usually about $109 before promotions",source:"https://www.thermoworks.com/products/thermapen-one",sourceLabel:"Thermapen ONE specifications",merchant:"ThermoWorks",affiliateProgram:"ThermoWorks opportunity—terms unverified",specs:{response:"1 second",accuracy:"±0.5°F from -4 to 248°F",range:"-58 to 572°F",protection:"IP67",warranty:"5 years"},environments:["restaurant","catering","senior living"],scores:{workflowFit:96,durability:93,sanitation:94,performance:98,serviceability:86,value:84,evidenceQuality:96,environmentFit:95}}),
  product({id:"thermoworks-thermopop-2",workflowId:"better-thermometer",manufacturer:"ThermoWorks",model:"ThermoPop 2",category:"Value instant-read thermometer",badge:"Best value",bestFor:"Credible accuracy and waterproofing at a lower entry price",why:"It preserves the operational essentials—documented accuracy, IP67 protection, readable rotating display, and calibration paperwork—without Thermapen pricing.",strengths:["2–3 second response","IP67 waterproof","Large rotating display"],tradeoff:"Slower than a thermocouple flagship and uses a coin cell.",skipIf:"Your team performs enough checks that every second compounds.",notes:"The 8-inch probe adds reach but has a slower stated response.",price:"Usually around $35",source:"https://commercial-food.thermoworks.com/products/thermopop-2",sourceLabel:"ThermoPop 2 specifications",merchant:"ThermoWorks Commercial",affiliateProgram:"ThermoWorks opportunity—terms unverified",specs:{response:"2–3 seconds",accuracy:"±1°F from 14 to 208°F",range:"-58 to 572°F",protection:"IP67"},environments:["home","restaurant","catering"],scores:{workflowFit:92,durability:86,sanitation:92,performance:88,serviceability:80,value:96,evidenceQuality:96,environmentFit:91}}),
  product({id:"comark-pdt300",workflowId:"better-thermometer",manufacturer:"Comark",model:"PDT300",category:"Waterproof pocket thermometer",badge:"Best low-cost commercial pocket unit",bestFor:"Stations prioritizing waterproofing, recalibration, and replacement cost",why:"A practical pocket format with a waterproof rating and field recalibration instead of disposable-gadget positioning.",strengths:["Waterproof","Field recalibratable","Thin tip"],tradeoff:"Six-second stated response is notably slower.",skipIf:"Rapid protein checks dominate the workflow.",notes:"Treat it as a station tool, not a substitute for a logged calibration program.",price:"Often $20–$35",source:"https://www.comarkinstruments.net/wp-content/uploads/2017/04/20541-1-PDT300-datasheet-USA.pdf",sourceLabel:"Comark PDT300 manufacturer data sheet",merchant:"Comark dealer channel",specs:{response:"6 seconds",range:"-40 to 392°F",protection:"Waterproof",calibration:"Field recalibratable"},environments:["restaurant","institutional"],scores:{workflowFit:82,durability:80,sanitation:88,performance:76,serviceability:82,value:91,evidenceQuality:88,environmentFit:84}}),
  product({id:"cooper-atkins-dfp450w",workflowId:"better-thermometer",manufacturer:"Cooper-Atkins",model:"DFP450W",category:"Institutional pocket thermometer",badge:"Best familiar institutional format",bestFor:"Teams already standardized on Cooper-Atkins foodservice instruments",why:"The familiar waterproof pocket format and broad dealer distribution reduce training and replacement friction.",strengths:["Waterproof format","Foodservice distribution","Pocket clip"],tradeoff:"Online model-level documentation is less transparent than the leaders.",skipIf:"You require a one-second response and included traceable certificate.",notes:"Confirm calibration-document requirements with compliance leadership.",price:"Often $25–$45",source:"https://www.cooper-atkins.com/",sourceLabel:"Cooper-Atkins manufacturer catalog",merchant:"Cooper-Atkins dealer",evidenceStrength:"moderate",specs:{range:"-40 to 450°F",protection:"Waterproof",functions:"Hold and min/max"},environments:["senior living","healthcare","institutional"],scores:{workflowFit:84,durability:84,sanitation:88,performance:78,serviceability:87,value:83,evidenceQuality:70,environmentFit:89}}),
  product({id:"thermoworks-chefalarm",workflowId:"better-thermometer",manufacturer:"ThermoWorks",model:"ChefAlarm",category:"Leave-in probe thermometer",badge:"Best monitored-cook companion",bestFor:"Roasts, cooling checks, and processes where the probe stays in place",why:"Replaceable probes, high and low alarms, and a separate timer make it a workflow tool rather than another instant-read duplicate.",strengths:["High/low alarms","Replaceable probes","Built-in timer"],tradeoff:"Cable management and probe care add work.",skipIf:"You only need fast spot checks.",notes:"Keep a compatible spare probe; probes are predictable wear items.",price:"Usually about $65",source:"https://www.thermoworks.com/chefalarm/",sourceLabel:"ChefAlarm specifications",merchant:"ThermoWorks",affiliateProgram:"ThermoWorks opportunity—terms unverified",specs:{range:"-58 to 572°F",alarms:"High and low",probe:"Replaceable Pro-Series"},environments:["home","restaurant","catering"],scores:{workflowFit:86,durability:84,sanitation:76,performance:89,serviceability:92,value:86,evidenceQuality:91,environmentFit:84}}),

  product({id:"eatwell-8-piece",workflowId:"memory-care-dining",manufacturer:"Eatwell",model:"8-Piece Assistive Tableware Set",category:"Coordinated high-contrast tableware",badge:"Best integrated memory-care set",bestFor:"A supervised trial where contrast, stability, and easier scooping must work together",why:"It approaches the meal as a coordinated system and publishes meaningful care and supervision instructions.",strengths:["High contrast","Slanted bowls","Anti-tip and anti-slip features"],tradeoff:"Piece-specific care instructions and premium set cost.",skipIf:"Only one targeted adaptation is needed or the supplied pieces conflict with the care plan.",notes:"Trial with the resident and interdisciplinary care team; color is not a clinical intervention.",price:"Manufacturer showed $98 sale / $110 regular when checked",source:"https://www.eatwellset.com/product-page/8-piece-eatwell-assistive-tableware-set",sourceLabel:"Eatwell product and care guidance",merchant:"Eatwell",specs:{contents:"2 bowls, 2 spoons, 2 cups, 2 lids",design:"High contrast and anti-slip",care:"Piece-specific dishwasher guidance"},environments:["home","senior living","supportive dining"],scores:{workflowFit:94,durability:78,sanitation:82,performance:88,serviceability:72,value:79,evidenceQuality:86,environmentFit:90}}),
  product({id:"ornamin-902",workflowId:"memory-care-dining",manufacturer:"ORNAMIN",model:"902 Plate with Sloped Base",category:"Supportive high-contrast plate",badge:"Best discreet supportive plate",bestFor:"Diners who benefit from a conventional-looking plate with easier food collection",why:"The adaptive geometry is visually restrained, supporting dignity while giving the diner a practical edge to work against.",strengths:["Sloped base","Multiple colors","Institutional positioning"],tradeoff:"Imported availability varies and melamine requires policy review.",skipIf:"Your operation prohibits melamine or needs oven-safe ware.",notes:"Choose contrast against both food and tabletop; do not use one color for every resident.",price:"Dealer/import quote required",source:"https://www.ornamin.com/media/a3/59/c1/1622540228/ORNAMIN_Sortiment_gesamt_EN.pdf",sourceLabel:"ORNAMIN care tableware catalog",merchant:"ORNAMIN dealer inquiry",specs:{diameter:"20 cm",material:"Melamine",design:"Sloped base"},environments:["home","senior living","institutional"],scores:{workflowFit:91,durability:85,sanitation:81,performance:86,serviceability:76,value:76,evidenceQuality:88,environmentFit:91}}),
  product({id:"carlisle-kingline-kl200",workflowId:"memory-care-dining",manufacturer:"Carlisle Kingline",model:"KL200 Red 9-inch Plate",category:"Commercial high-contrast dinnerware",badge:"Best scalable contrast fleet",bestFor:"Communities testing high-contrast place settings at commercial scale",why:"Commercial durability, stackability, and familiar geometry are easier to operationalize than a specialty set.",strengths:["Commercial durability","Stackable","Conventional appearance"],tradeoff:"No built-in scoop edge and often sold by case.",skipIf:"The diner needs physical food-control geometry rather than only contrast.",notes:"Pilot a small quantity and measure real outcomes before changing the whole dining room.",price:"Commercial case pricing varies",source:"https://www.carlislefsp.com/dinnerware/kingline-dinnerware/",sourceLabel:"Carlisle Kingline manufacturer page",merchant:"Carlisle dealer",specs:{diameter:"9 inches",material:"Heavy-weight melamine",care:"Commercial dishwasher line"},environments:["senior living","institutional","restaurant"],scores:{workflowFit:83,durability:92,sanitation:90,performance:76,serviceability:91,value:86,evidenceQuality:76,environmentFit:92}}),
  product({id:"kennedy-cup",workflowId:"memory-care-dining",manufacturer:"Kinsman",model:"Kennedy Spillproof Cup",category:"Spill-resistant drinkware",badge:"Best simple spill-control cup",bestFor:"Caregiver-supervised settings needing a lightweight spill-resistant cup",why:"Simple construction and wide specialty distribution make replacement easier than proprietary drinkware systems.",strengths:["Simple","Lightweight","Widely distributed"],tradeoff:"Small capacity and not appropriate for every swallowing plan.",skipIf:"The plan restricts straws or requires flow-controlled drinking equipment.",notes:"Confirm fit with nursing, SLP, OT, and the resident care plan where applicable.",price:"Often $10–$18",source:"https://www.performancehealth.com/kennedy-cup",sourceLabel:"Kennedy Cup specialty merchant reference",merchant:"Performance Health",affiliateProgram:"Performance Health opportunity—terms unverified",evidenceStrength:"moderate",sourceType:"merchant",specs:{capacity:"7 ounces",design:"Threaded lid",use:"Straw-compatible"},environments:["home","senior living","supportive dining"],scores:{workflowFit:81,durability:74,sanitation:75,performance:78,serviceability:88,value:89,evidenceQuality:66,environmentFit:82}}),
  product({id:"maddak-redware-set",workflowId:"memory-care-dining",manufacturer:"Maddak",model:"Redware Dinnerware Set",category:"High-contrast adaptive dinnerware",badge:"Best straightforward contrast trial",bestFor:"Care teams wanting to trial visual contrast without replacing every piece",why:"It offers an understandable contrast trial while retaining familiar tableware forms.",strengths:["Visible contrast","Simple deployment","Specialty distribution"],tradeoff:"Resident-specific outcomes remain uncertain.",skipIf:"The diner needs flow control or a different prescribed support more than color and scoop geometry.",notes:"Document independence, spills, cueing, preference, and intake instead of assuming success.",price:"Performance Health showed $16.71–$84.30 by piece or set",source:"https://www.performancehealth.com/maddak-redware-tableware",sourceLabel:"Maddak Redware specialty merchant reference",merchant:"Performance Health",affiliateProgram:"Performance Health opportunity—terms unverified",evidenceStrength:"moderate",sourceType:"merchant",specs:{color:"Red high contrast",contents:"Basic and deluxe sets",care:"Dishwasher, autoclave, and microwave claims by seller"},environments:["home","senior living","supportive dining"],scores:{workflowFit:82,durability:76,sanitation:80,performance:78,serviceability:82,value:81,evidenceQuality:72,environmentFit:82}}),

  product({id:"robot-coupe-mp450",workflowId:"immersion-blender",manufacturer:"Robot-Coupe",model:"MP 450 Ultra V.V.",category:"Variable-speed commercial immersion blender",badge:"Best overall commercial",bestFor:"Frequent soups, sauces, and purées in deep production vessels",why:"A removable bell and blade materially improve sanitation and maintenance, backed by an established service platform.",strengths:["Removable bell and blade","Variable speed","Established parts ecosystem"],tradeoff:"Capital cost and weight are excessive for small batches.",skipIf:"Most batches are under ten liters.",notes:"Match shaft length to vessel depth; longer is not automatically more ergonomic.",price:"Often roughly $900–$1,300",source:"https://www.robot-coupe.com/uk/en_GB/p/immersion-blender-mp-450-ultra-v-v/18266",sourceLabel:"MP 450 Ultra V.V. manufacturer page",merchant:"Robot-Coupe dealer",specs:{shaft:"450 mm",speed:"Variable",cleaning:"Removable bell and blade"},environments:["restaurant","catering","senior living","institutional"],scores:{workflowFit:97,durability:94,sanitation:95,performance:96,serviceability:95,value:82,evidenceQuality:93,environmentFit:96}}),
  product({id:"waring-wsb50",workflowId:"immersion-blender",manufacturer:"Waring",model:"WSB50 12-inch Big Stik",category:"Heavy-duty immersion blender",badge:"Best value heavy-duty",bestFor:"Forty-quart-class work where interchangeable shafts and parts matter",why:"The 750-watt platform, NSF listing, shaft family, and replacement kits create a pragmatic commercial value proposition.",strengths:["750 watts","Interchangeable shafts","Replacement kits"],tradeoff:"A ten-pound tool with a one-year warranty.",skipIf:"Operators need a lighter variable-speed unit.",notes:"Budget for a bowl clamp when long blending runs would create fatigue.",price:"Often $500–$750",source:"https://www.waring.com/on/demandware.static/-/Sites-waring-master/default/dwd8f34315/pdf/specSheet/wsb50-big-stik-immersion-blender-spec-sheet-090921%5B1%5D.pdf",sourceLabel:"WSB50 specification sheet",merchant:"Waring dealer",specs:{shaft:"12 inches",power:"750 watts",speed:"18,000 RPM max",certification:"ETL, NSF"},environments:["restaurant","catering"],scores:{workflowFit:91,durability:89,sanitation:86,performance:92,serviceability:92,value:91,evidenceQuality:94,environmentFit:90}}),
  product({id:"dynamic-mx91",workflowId:"immersion-blender",manufacturer:"Dynamic",model:"Master MX91",category:"Fixed-speed commercial immersion blender",badge:"Best proven simple workhorse",bestFor:"Operations favoring a straightforward platform with parts support",why:"A simple commercial lineage makes the tool easy to train, understand, service, and replace.",strengths:["Simple controls","Commercial lineage","Parts pathway"],tradeoff:"Fixed speed and a large form factor.",skipIf:"Variable speed is important for delicate emulsions or small batches.",notes:"Confirm model suffix and voltage; regional variants are not interchangeable assumptions.",price:"Often $650–$900",source:"https://www.dynamicmixersusa.com/wp-content/uploads/2020/01/specsheets-dynamic-MX91.pdf",sourceLabel:"Dynamic MX91 specification sheet",merchant:"Dynamic Mixers USA",specs:{shaft:"16-inch class",motor:"Commercial fixed speed",service:"Replaceable parts"},environments:["restaurant","catering","institutional"],scores:{workflowFit:89,durability:91,sanitation:84,performance:90,serviceability:90,value:84,evidenceQuality:89,environmentFit:90}}),
  product({id:"sammic-xm51",workflowId:"immersion-blender",manufacturer:"Sammic",model:"XM-51",category:"Continuous-use immersion blender",badge:"Best for sustained institutional batches",bestFor:"Repeat soup, sauce, and texture-modified production up to the stated 80-liter class",why:"Sammic explicitly states continuous use, a detachable arm, and a maximum vessel capacity—useful planning facts.",strengths:["570 watts","425 mm detachable arm","80-liter stated capacity"],tradeoff:"Fixed speed and regional sourcing.",skipIf:"You need very small-batch finesse or local service is weak.",notes:"Continuous-use capability does not eliminate ergonomic limits; rotate work and use support.",price:"Regional dealer quote required",source:"https://sammic.co.uk/product/hand-blender-xm-51",sourceLabel:"Sammic XM-51 specifications",merchant:"Sammic dealer",specs:{power:"570 watts",shaft:"425 mm",capacity:"80 liters",speed:"12,000 RPM"},environments:["senior living","institutional","catering"],scores:{workflowFit:94,durability:92,sanitation:92,performance:92,serviceability:84,value:82,evidenceQuality:96,environmentFit:94}}),
  product({id:"hamilton-hmi200",workflowId:"immersion-blender",manufacturer:"Hamilton Beach Commercial",model:"HMI200 BigRig",category:"Commercial immersion blender",badge:"Best alternate dealer network",bestFor:"Operators already supported by Hamilton Beach Commercial dealers",why:"It provides another legitimate commercial service channel where local support for other brands is weak.",strengths:["Commercial platform","Dealer support","Configuration range"],tradeoff:"Exact HMI200 configuration must be verified.",skipIf:"The local dealer cannot document parts and response time.",notes:"Buy the exact shaft and electrical configuration, not only the family name.",price:"Configured dealer quote required",source:"https://hamiltonbeachcommercial.com/wp-content/uploads/2018/09/HMI200_Immersion_Blender.pdf",sourceLabel:"HMI200 series sheet",merchant:"Hamilton Beach Commercial",specs:{series:"HMI200",application:"Blend, chop, purée, emulsify",support:"Commercial channel"},environments:["restaurant","catering"],scores:{workflowFit:84,durability:85,sanitation:82,performance:84,serviceability:87,value:80,evidenceQuality:79,environmentFit:85}}),

  product({id:"bunn-cwtf15",workflowId:"coffee-setup",manufacturer:"BUNN",model:"CWTF15-APS 23001.0017",category:"Plumbed airpot batch brewer",badge:"Best community coffee station",bestFor:"Senior-living, meeting, and hospitality stations needing portable insulated service",why:"The narrow footprint, airpot workflow, plumbed operation, pourover backup, and published service documents make it operationally legible.",strengths:["9-inch width","1.9–3 L airpots","Pourover backup"],tradeoff:"Servers and water treatment are separate.",skipIf:"You need advanced recipe profiling.",notes:"Budget two airpots, cleaning tools, filters, and water treatment—not just the brewer.",price:"Often $850–$1,200 before servers and installation",source:"https://commercial.bunn.com/23001.0017",sourceLabel:"CWTF15-APS specifications",merchant:"BUNN dealer",specs:{electrical:"120V, 1370W",width:"9 inches",server:"1.9–3 L airpot",water:"Plumbed"},environments:["café","senior living","institutional"],scores:{workflowFit:95,durability:92,sanitation:88,performance:90,serviceability:96,value:88,evidenceQuality:97,environmentFit:96}}),
  product({id:"fetco-cbs2131",workflowId:"coffee-setup",manufacturer:"FETCO",model:"CBS-2131XTS",category:"Programmable batch brewer",badge:"Best programmable batch control",bestFor:"Programs needing repeatable recipes and more control than a basic airpot brewer",why:"FETCO’s commercial platform fits operations that can support recipe calibration, training, and maintenance.",strengths:["Programmable recipes","Commercial support","Batch consistency"],tradeoff:"More complexity and dealer configuration.",skipIf:"You need a minimal-training coffee station.",notes:"No brewer compensates for stale coffee, inconsistent grinding, or untreated water.",price:"Quote-based four-figure brewer system",source:"https://www.fetco.com/brewers",sourceLabel:"FETCO brewer catalog",merchant:"FETCO dealer",evidenceStrength:"moderate",specs:{station:"Single",controls:"XTS touchscreen family",server:"Selected separately"},environments:["café","institutional","hospitality"],scores:{workflowFit:90,durability:91,sanitation:87,performance:94,serviceability:90,value:80,evidenceQuality:79,environmentFit:90}}),
  product({id:"mahlkonig-guatemala",workflowId:"coffee-setup",manufacturer:"Mahlkönig",model:"Guatemala 2.0",category:"Commercial filter coffee grinder",badge:"Best commercial batch grinder",bestFor:"Programs grinding full batch-brew doses or bags repeatedly",why:"This is a purpose-built filter-production grinder, not a home grinder stretched into a commercial role.",strengths:["Batch workflow","Commercial flat-burr platform","Dealer service"],tradeoff:"Large capital purchase and not an espresso solution.",skipIf:"Volume is low or espresso is the main job.",notes:"Set recipes by beverage yield and grinder setting, then verify with tasting and measurements.",price:"Often $1,800–$2,500",source:"https://www.mahlkoenig.us/products/guatemala-2-0",sourceLabel:"Guatemala 2.0 manufacturer page",merchant:"Mahlkönig dealer",specs:{application:"Filter batch grinding",workflow:"Bag and batch",support:"Commercial dealer"},environments:["café","senior living","institutional"],scores:{workflowFit:93,durability:94,sanitation:82,performance:94,serviceability:91,value:80,evidenceQuality:82,environmentFit:92}}),
  product({id:"acaia-pearl",workflowId:"coffee-setup",manufacturer:"Acaia",model:"Pearl AP007/AP008/AP009",category:"Coffee brewing scale",badge:"Best brew-control scale",bestFor:"Programs that will use weight and time to standardize recipes",why:"Fast readable measurement, integrated timing, and a brewing-focused platform make it useful for training and recipe discipline.",strengths:["2,000 g capacity","0.1 g readability","Integrated timer"],tradeoff:"Premium price and not washdown equipment.",skipIf:"Staff will not weigh inputs and beverage yield.",notes:"Keep it away from steam and standing water; establish a charging routine.",price:"Manufacturer listed $150 when checked",source:"https://acaia.co/collections/coffee-scales/products/pearl",sourceLabel:"Acaia Pearl specifications",merchant:"Acaia",specs:{capacity:"2,000 g",readability:"0.1 g",battery:"30–40 hours",connectivity:"Bluetooth 5.0"},environments:["home","café","hospitality"],scores:{workflowFit:88,durability:80,sanitation:72,performance:94,serviceability:83,value:80,evidenceQuality:96,environmentFit:84}}),
  product({id:"baratza-forte",workflowId:"coffee-setup",manufacturer:"Baratza",model:"Forté AP ZCG1085",category:"Compact all-purpose grinder",badge:"Best compact mixed-use grinder",bestFor:"Low-volume programs needing espresso-to-filter range in a serviceable footprint",why:"Broad adjustment and Baratza’s parts-oriented support make it a credible bridge between home and light-commercial work.",strengths:["54 mm flat ceramic burrs","Macro/micro adjustment","Parts support"],tradeoff:"Not a high-volume primary café grinder.",skipIf:"You grind repeated full batch-brew doses all day.",notes:"Choose a primary use and dial-in protocol; all-purpose capability can create inconsistency.",price:"Usually around $850–$900",source:"https://www.baratza.com/en-us/product/forte-ap-zcg1085",sourceLabel:"Forté AP manufacturer page",merchant:"Baratza",affiliateProgram:"Breville/Baratza opportunity—terms unverified",specs:{burrs:"54 mm flat ceramic",dosing:"Weight, time, manual",positioning:"Light commercial"},environments:["home","café","hospitality"],scores:{workflowFit:84,durability:84,sanitation:78,performance:88,serviceability:94,value:80,evidenceQuality:88,environmentFit:81}}),

  product({id:"maddak-inner-lip",workflowId:"adaptive-dining",manufacturer:"Maddak",model:"Inner Lip Plate",category:"Adaptive scoop plate",badge:"Best simple scoop plate",bestFor:"Diners who push food across the plate and need an edge to work against",why:"It targets one clear task with a familiar plate form, making it easy to trial.",strengths:["Focused function","Familiar form","Low training burden"],tradeoff:"No universal non-slip base and fit must be observed.",skipIf:"The challenge is grip, drinking, vision, or safe swallowing rather than scooping.",notes:"Pair with non-slip support only after confirming stability and cleanability.",price:"Often $15–$30",source:"https://specialneedsessentials.com/collections/daily-living/products/redware-inner-lip-plate-red",sourceLabel:"Maddak specialty merchant reference",merchant:"Special Needs Essentials",evidenceStrength:"moderate",sourceType:"merchant",specs:{design:"Inner lip",appearance:"Round plate",use:"Scooping support"},environments:["home","caregiver","senior living"],scores:{workflowFit:88,durability:77,sanitation:78,performance:84,serviceability:84,value:88,evidenceQuality:66,environmentFit:84}}),
  product({id:"sammons-bendable",workflowId:"adaptive-dining",manufacturer:"Sammons Preston",model:"Sure Grip Bendable Utensils",category:"Adaptive utensils",badge:"Best configurable utensil set",bestFor:"Diners whose wrist range or grip benefits from a larger handle and adjusted angle",why:"The product addresses grip and approach angle directly, with individual pieces avoiding unnecessary kit purchases.",strengths:["Bendable shaft","Built-up handle","Individual options"],tradeoff:"Needs individual setup and is not right for every hand pattern.",skipIf:"Weighted input, a cuff, or specialized feeding support is required.",notes:"Have OT or the care team establish the bend; do not improvise without the diner.",price:"Seller showed $11.69–$41.50 by piece or set",source:"https://www.performancehealth.com/sure-grip-bendable-utensil",sourceLabel:"Sammons Preston Sure Grip product page",merchant:"Performance Health",affiliateProgram:"Performance Health opportunity—terms unverified",evidenceStrength:"moderate",specs:{shaft:"Bendable",handle:"1.5-inch built-up rubber",options:"Fork, spoons, rocker knife"},environments:["home","caregiver","senior living","supportive dining"],scores:{workflowFit:91,durability:78,sanitation:82,performance:86,serviceability:86,value:84,evidenceQuality:78,environmentFit:87}}),
  product({id:"dycem-mat",workflowId:"adaptive-dining",manufacturer:"Dycem",model:"Non-Slip Rectangular Mat",category:"Non-slip dining support",badge:"Best low-cost stability aid",bestFor:"Plates or bowls that slide on trays and tables",why:"It solves a common mechanical problem without changing the dish or utensil and is easy to trial.",strengths:["Reusable","Washable","High-contrast colors"],tradeoff:"Must be cleaned and can be misplaced or folded.",skipIf:"The surface cannot stay clean and flat or fixed mounting is needed.",notes:"Assign cleaning ownership and replacement criteria; a dirty mat is not dignified support.",price:"Often $15–$30 by size",source:"https://www.dycem-ns.com/files/healthcare-brochure.pdf",sourceLabel:"Dycem healthcare dining guide",merchant:"Dycem",specs:{function:"Stabilizes dining items",material:"Reusable polymer",care:"Washable"},environments:["home","caregiver","senior living","institutional"],scores:{workflowFit:89,durability:82,sanitation:77,performance:86,serviceability:90,value:94,evidenceQuality:87,environmentFit:90}}),
  product({id:"independence-mug",workflowId:"adaptive-dining",manufacturer:"Performance Health",model:"Independence 081003854 Two-Handled Mug",category:"Adaptive drinking cup",badge:"Best two-handled cup",bestFor:"Diners who gain stability by using both hands",why:"The two-handle, wide-base form with two lid options is understandable without looking like complex feeding equipment.",strengths:["Two large handles","Wide base","Spout and anti-splash lids"],tradeoff:"Polycarbonate feel and lid choice materially affect fit.",skipIf:"The swallowing plan requires prescribed flow control.",notes:"Never substitute a cup choice for swallowing assessment or supervision requirements.",price:"Current distributor price must be checked",source:"https://mms.mckesson.com/product/555350/Performance-Health-1251",sourceLabel:"McKesson listing with manufacturer SKU and specifications",merchant:"McKesson",evidenceStrength:"moderate",sourceType:"merchant",specs:{capacity:"10 ounces",material:"Clear polycarbonate",lids:"Spout and anti-splash"},environments:["home","caregiver","senior living"],scores:{workflowFit:86,durability:79,sanitation:79,performance:82,serviceability:86,value:84,evidenceQuality:78,environmentFit:84}}),
  product({id:"oxo-good-grips",workflowId:"adaptive-dining",manufacturer:"OXO",model:"Good Grips Stainless Steel Utensils",category:"Large-handle dining utensils",badge:"Best familiar large-handle option",bestFor:"Home and caregiver settings where a larger softer grip is enough",why:"A familiar appearance and broad grip can improve usability without making the place setting feel clinical.",strengths:["Broad grip","Familiar appearance","Easy retail replacement"],tradeoff:"Not bendable or therapeutically weighted.",skipIf:"Prescribed weight, angle, cuff, or stabilization is needed.",notes:"Use only when grip size is the actual problem being solved.",price:"Usually $10–$18 per piece or set-dependent",source:"https://www.oxo.com/shop/kitchenware/tabletop/flatware.html",sourceLabel:"OXO flatware catalog",merchant:"OXO",affiliateProgram:"OXO opportunity—terms unverified",specs:{handle:"Broad non-slip grip",material:"Stainless utensil",positioning:"Universal design"},environments:["home","caregiver","senior living"],scores:{workflowFit:77,durability:82,sanitation:84,performance:74,serviceability:92,value:88,evidenceQuality:72,environmentFit:78}}),

  product({id:"kitchenaid-ksm8990",workflowId:"commercial-mixer",manufacturer:"KitchenAid",model:"Commercial KSM8990 8-Quart",category:"Commercial countertop planetary mixer",badge:"Best small commercial operation",bestFor:"Low-volume cafés, catering prep, and pastry batches needing NSF commercial certification",why:"It offers commercial certification, stainless tools, and a familiar footprint without pretending to be a 20-quart production machine.",strengths:["8-quart bowl","NSF commercial certification","Stainless tools"],tradeoff:"Limited headroom for repeated heavy dough.",skipIf:"Your real batch plan already exceeds eight quarts.",notes:"Size from the heaviest real recipe and frequency, not bowl volume alone.",price:"Usually $900–$1,100",source:"https://www.kitchenaid.com/countertop-appliances/stand-mixers/bowl-lift-stand-mixers/p.nsf-certified-commercial-series-8-quart-bowl-lift-stand-mixer.KSM8990WH.html",sourceLabel:"KitchenAid KSM8990 product page",merchant:"KitchenAid Commercial",affiliateProgram:"KitchenAid opportunity—terms unverified",specs:{capacity:"8 quarts",motor:"Commercial DC platform",certification:"NSF commercial",warranty:"Verify current terms"},environments:["café","bakery","catering"],scores:{workflowFit:88,durability:83,sanitation:90,performance:84,serviceability:84,value:85,evidenceQuality:94,environmentFit:88}}),
  product({id:"vollrath-40755",workflowId:"commercial-mixer",manufacturer:"Vollrath",model:"40755 MIX1007 7-Quart",category:"Commercial countertop planetary mixer",badge:"Best compact commercial value",bestFor:"Small prep programs needing a guarded commercial mixer",why:"Published electrical and capacity data, a bowl guard, and commercial support make it straightforward to specify.",strengths:["7 quarts","Five speeds","Bowl guard"],tradeoff:"Limited capacity and heavy-dough headroom.",skipIf:"Growth will quickly require ten or twenty quarts.",notes:"Check maximum recipe weights in the manual before treating it as a dough mixer.",price:"Often $900–$1,300",source:"https://www.vollrathfoodservice.com/products/countertop-equipment/food-preparation-equipment/mixers/countertop-mixers-7-qt/40755",sourceLabel:"Vollrath 40755 product page",merchant:"Vollrath dealer",specs:{capacity:"7 quarts",motor:"1/3 HP",speeds:"5",electrical:"110–120V"},environments:["café","bakery","hospitality"],scores:{workflowFit:84,durability:85,sanitation:88,performance:80,serviceability:86,value:82,evidenceQuality:95,environmentFit:84}}),
  product({id:"globe-sp20",workflowId:"commercial-mixer",manufacturer:"Globe",model:"SP20 20-Quart",category:"Mid-volume bench mixer",badge:"Best value 20-quart workhorse",bestFor:"General-purpose mid-volume kitchens needing a gear-driven 20-quart platform",why:"Globe publishes recipe capacities, transmission details, speed data, and a two-year warranty—the information operators need.",strengths:["Gear-driven","Published capacity chart","2-year warranty"],tradeoff:"Fixed speeds and a heavy countertop footprint.",skipIf:"You require Hobart’s service footprint or advanced interlocks.",notes:"Capacity charts are limits, not daily production targets; leave headroom.",price:"Often $3,000–$4,500",source:"https://globefoodequip.com/products/mixers/bench-mixers/sp20.html",sourceLabel:"Globe SP20 specifications",merchant:"Globe dealer",specs:{capacity:"20 quarts",motor:"1/2 HP",speeds:"104, 194, 353 RPM",transmission:"Gear driven"},environments:["restaurant","bakery","café","institutional"],scores:{workflowFit:93,durability:92,sanitation:90,performance:92,serviceability:88,value:91,evidenceQuality:97,environmentFit:93}}),
  product({id:"hobart-hl200",workflowId:"commercial-mixer",manufacturer:"Hobart",model:"Legacy+ HL200 20-Quart",category:"Maximum heavy-duty countertop mixer",badge:"Best institutional service platform",bestFor:"High-consequence kitchens prioritizing service coverage, safety, and long support",why:"Safety interlocks, capacity data, training resources, and the service ecosystem justify the premium where downtime is expensive.",strengths:["Triple interlock","Soft start and timer","Service ecosystem"],tradeoff:"High capital cost and 189-pound machine weight.",skipIf:"A lower-cost 20-quart mixer has adequate local service and workload fit.",notes:"Evaluate cart, electrical, attachments, maintenance, and local response time in total installed cost.",price:"Often $8,000–$12,000+ configured",source:"https://www.hobartcorp.com/products/food-prep/mixers/legacy-plus-countertop-mixer",sourceLabel:"Hobart Legacy+ mixer page",merchant:"Hobart sales and service",specs:{capacity:"20 quarts",speeds:"Stir plus 3",safety:"Triple interlock",weight:"189 lb less bowl"},environments:["restaurant","bakery","senior living","institutional"],scores:{workflowFit:97,durability:98,sanitation:94,performance:97,serviceability:98,value:79,evidenceQuality:98,environmentFit:98}}),
  product({id:"varimixer-kodiak20",workflowId:"commercial-mixer",manufacturer:"Varimixer",model:"Kodiak 20",category:"Ergonomic 20-liter planetary mixer",badge:"Best ergonomic alternative",bestFor:"Operations valuing operator access and bowl handling alongside 20-liter capacity",why:"Kodiak emphasizes working height, visibility, handling, and hygienic surfaces—important when several people use the mixer daily.",strengths:["Ergonomic layout","20-liter tier","IP44 platform"],tradeoff:"Regional service and electrical configuration vary.",skipIf:"Local parts support is weaker than Globe or Hobart.",notes:"Service geography should carry as much weight as the specification sheet.",price:"Configured dealer quote required",source:"https://varimixer.com/produkt/kodiak/",sourceLabel:"Varimixer Kodiak manufacturer page",merchant:"Varimixer dealer",specs:{capacity:"20 liters",design:"Ergonomic bowl handling",protection:"IP44 platform"},environments:["restaurant","bakery","café","institutional"],scores:{workflowFit:91,durability:92,sanitation:94,performance:91,serviceability:82,value:82,evidenceQuality:92,environmentFit:91}}),
];

export const marketplaceCatalog = {
  harvest: { id: "product-harvest-001", checkedAt: checked, candidatesResearched: 34, rejected: 4, deeplyResearched: 30, disclosure: "Editorial scoring excludes affiliate availability and commission. Prices are context only and must be rechecked." },
  workflows,
  products,
};

export function productsForWorkflow(workflowId: WorkflowId) {
  return products.filter((item) => item.workflowId === workflowId);
}
