import type {ProductRecord} from "./catalog";

export type PublicationProfile={status:"publication_ready"|"discovery_only"|"verify";reviewedAt:string;sourceStatus:"verified"|"requires_review";sourceNotes:string;priceStatus:"observed"|"current_check_required"|"quote_required";specificationStatus:"verified"|"partial"};
type Profile={publication:PublicationProfile;specs?:Record<string,string>;sourceUrl?:string;sourceLabel?:string};
const reviewedAt="2026-08-13";
const verified=(sourceNotes:string,priceStatus:PublicationProfile["priceStatus"]="current_check_required"):PublicationProfile=>({status:"publication_ready",reviewedAt,sourceStatus:"verified",sourceNotes,priceStatus,specificationStatus:"verified"});
const review=(sourceNotes:string):PublicationProfile=>({status:"verify",reviewedAt,sourceStatus:"requires_review",sourceNotes,priceStatus:"current_check_required",specificationStatus:"partial"});

export const publicationProfiles:Record<string,Profile>={
"thermoworks-thermapen-one":{publication:verified("Official model page returned the exact Thermapen ONE identity and current specifications; checkout price still requires confirmation.","observed")},
"thermoworks-thermopop-2":{publication:verified("Official commercial product page returned the exact ThermoPop 2 identity and specifications.","observed")},
"thermoworks-chefalarm":{publication:verified("Official product page returned the exact ChefAlarm identity, probe system, alarms, and timer details.","observed")},
"victorinox-fibrox-8":{publication:verified("Official US product page returned model 5.2063.20 and the 8-inch Fibrox chef-knife identity."),specs:{bladeLength:"8 inches",handle:"Fibrox thermoplastic elastomer",manufacturerNumber:"5.2063.20"},sourceUrl:"https://www.victorinox.com/en-US/Products/Cutlery/Chef%27s-Knives/Fibrox%C2%AE-Chef%E2%80%99s-Knife-Extra-Wide/p/5.2063.20"},
"cambro-22sfscw":{publication:verified("Official CamSquares page returned the poly square-storage family; exact 22SFSCW regional stock remains merchant-dependent."),specs:{capacity:"22 qt model",shape:"Square",material:"Polycarbonate product family"},sourceUrl:"https://www.cambro.com/products/food-storage/square-food-storage-containers/camsquares-classic-food-storage-containers/camsquares-poly/"},
"vollrath-5220":{publication:verified("Official Wear-Ever sheet-pan page verified the model family; gauge and pack configuration require confirmation."),specs:{size:"Full-size sheet-pan class",material:"Aluminum Wear-Ever product family"}},
"fluke-62-max":{publication:verified("Official Fluke page returned the exact 62 MAX infrared-thermometer identity."),specs:{measurement:"Non-contact infrared surface temperature",protection:"IP54 product family",dropRating:"Manufacturer states 3 m drop testing"}},
"fieldpiece-sm480v":{publication:verified("Corrected official SM480V page verified the four-port manifold, micron gauge, IP54 design, and Job Link functions."),specs:{ports:"4",maximumPressure:"800 psig",wirelessRange:"Up to 1000 ft line of sight",protection:"IP54"},sourceUrl:"https://www.fieldpiece.com/product/sm480v-wireless-4-port-sman-refrigerant-manifold-and-micron-gauge/"},
"robot-coupe-r2n":{publication:verified("Official US page returned the exact R 2 N combination-processor identity."),specs:{productType:"Combination processor",market:"US commercial model"},sourceUrl:"https://www.robot-coupe.com/usa/en_US/p/combination-processors-r-2-n/18421"},
"robot-coupe-cl50":{publication:verified("Corrected official US CL 50 page verified power, voltage, speed, feed hoppers, and stated output."),specs:{power:"1.5 HP",voltage:"120 V single phase",speed:"425 rpm",statedOutput:"Up to 220 lb/hour"},sourceUrl:"https://www.robot-coupe.com/usa/en_US/p/vegetable-preparation-machines-cl-50-1v/20672"},
"waring-wfp16s":{publication:review("The official URL did not complete during bounded verification. Model-level details remain discovery-only pending a fresh official source check.")},
"vitamix-xl":{publication:verified("Official Vitamix Commercial page returned the exact Vitamix XL identity."),specs:{productType:"Commercial high-capacity blender",configuration:"Verify container and electrical SKU"}},
"vacmaster-vp215":{publication:review("The exact-model URL now resolves to an official search result rather than a stable product page. Current documentation needs a fresh official source.")},
"true-t-49-hc":{publication:verified("Official True model page and current specification sheet verified identity, dimensions, electrical load, shelves, operating range, and NSF/ANSI 7 status. Delivered and installed price remains quote-required.","quote_required"),specs:{configuration:"Two-section, 2 solid doors, 6 shelves",dimensions:"54 1/8 W × 29 1/2 D × 78 3/8 H inches",electrical:"115/60/1, 5.4 A, NEMA 5-15P",temperature:"33–38°F stated operating range",refrigerant:"R-290",certification:"NSF/ANSI Standard 7 for open food product",serviceability:"Bottom-mounted condensing unit; removable magnetic gaskets",warranty:"Current full warranty terms must be confirmed with quote"}},
"true-t-23f-hc":{publication:verified("Official True page returned the exact T-23F-HC identity."),specs:{configuration:"Single-section solid-door reach-in freezer",installation:"Verify electrical, clearance, doorway, and service access"}},
"turbo-air-m3r47":{publication:verified("Official M3 Series page and current M3R47-2-N specification sheet verified capacity, dimensions, electrical load, refrigerant, shelves, and published US warranty. Delivered and installed price remains quote-required.","quote_required"),specs:{configuration:"Two-section, 2 solid doors, 6 shelves",capacity:"42.3 cu ft",dimensions:"51 3/4 W × 30 3/4 D × 77 7/8 H inches, excluding noted rear enclosure/casters",electrical:"115/60/1, 2.8 A, NEMA 5-15P",refrigerant:"R-290",serviceability:"Top-mounted self-contained system; magnetic door gaskets",warranty:"Manufacturer sheet states 5-year parts/labor and 7-year compressor warranty in USA"}},
"traulsen-g20010":{publication:review("The former manufacturer URL returned 404. A current ENERGY STAR record verifies identity and dimensions, but a stable current manufacturer page is still needed."),specs:{volume:"46.02 cu ft (ENERGY STAR)",dimensions:"52.13 W × 35 D × 83.44 H inches (ENERGY STAR)",refrigerant:"R-290 (ENERGY STAR)"},sourceUrl:"https://www.energystar.gov/productfinder/product/certified-commercial-refrigerators-and-freezers/details/3477667/export/pdf",sourceLabel:"Current ENERGY STAR G20010 certification record"},
"hoshizaki-km-520maj":{publication:verified("Official Hoshizaki page returned the exact KM-520MAJ air-cooled crescent-cuber identity."),specs:{iceType:"Crescent cube",condenser:"Air-cooled modular unit",installation:"Size bin, water treatment, drain, and electrical requirements"}},
"hobart-am16":{publication:verified("Corrected official AM16 Base page verified water use and configuration-dependent throughput.","quote_required"),specs:{waterUse:"0.67 gallons per rack",throughput:"40–60 racks/hour for Base configurations",sanitization:"Hot water; configuration dependent"},sourceUrl:"https://www.hobartcorp.com/products/commercial-dishwashers/door-type/hobart-am16-base-door-type-commercial-dishwasher"},
"alto-shaam-750-s":{publication:verified("Official Alto-Shaam page returned the exact 750-S low-temperature holding-cabinet identity."),specs:{technology:"Halo Heat holding",configuration:"Verify voltage, door, pan, and regional configuration"}},
"square-restaurants":{publication:verified("Official US page verified Square for Restaurants; plan pricing and hardware remain current-contract facts."),specs:{productType:"Restaurant POS software and hardware ecosystem",pricing:"Verify current plan, processing, hardware, and contract terms"}},
"toast-pos":{publication:verified("Official Toast URL remains current but returned an automated-access challenge; public indexing verified the restaurant POS identity. Terms need manual review."),specs:{productType:"Restaurant POS platform",pricing:"Quote and contract terms required"}},
"marginedge-platform":{publication:verified("Official MarginEdge source verified invoice, food-cost, and restaurant-management positioning; pricing and integrations need confirmation."),specs:{functions:"Invoice processing, food-cost visibility, operational reporting",pricing:"Verify current plan and implementation terms"}},
"simplythick-easymix":{publication:verified("Official SimplyThick source verifies EasyMix positioning; use must follow the care plan and current manufacturer directions."),specs:{productType:"Gel thickener",clinicalBoundary:"Use only under the applicable care plan and qualified clinical direction"}},
"robot-coupe-blixer-4":{publication:verified("Corrected official US Blixer 4 page verified bowl, speed, and stated portion range."),specs:{bowl:"4.5 qt",speed:"3450 rpm",statedPortions:"2–15 portions at 200 g",clinicalBoundary:"Texture outcomes require validated recipes and clinical protocols"},sourceUrl:"https://www.robot-coupe.com/usa/en_US/p/blixer-blixer-4/18384"},
};

export function applyPublicationProfile(product:ProductRecord):ProductRecord{const profile=publicationProfiles[product.id];if(!profile)return product;const evidence=profile.sourceUrl?[{...product.evidence[0],url:profile.sourceUrl,label:profile.sourceLabel??product.evidence[0].label,checked:reviewedAt},...product.evidence.slice(1)]:product.evidence;const price=profile.publication.priceStatus==="quote_required"?{context:"Manufacturer quote required; delivered and installed cost is not published",checked:reviewedAt}:product.price;return {...product,publication:profile.publication,price,specs:{...product.specs,...profile.specs},evidence,merchants:product.merchants.map((merchant,index)=>index===0&&profile.sourceUrl?{...merchant,url:profile.sourceUrl,checked:reviewedAt}:merchant),image:{...product.image,referenceUrl:profile.sourceUrl??product.image.referenceUrl,rightsSource:"Manufacturer page provides reference imagery but no reuse grant was identified.",rightsChecked:reviewedAt}};}
