import {requireMarketplaceAdministrator} from "../../../marketplace-authorization";
import {applicationPriority} from "../../../growth/application-priority";
import {chefGringoApplicationProfile} from "../../../growth/application-profile";
import {partnerHuntFixtures} from "../../../growth/partner-hunt-fixtures";
import {readiness} from "../../../growth/partner-hunt";
import {getEmailCaptureHealth} from "../../../lib/engagement/emailHealth";
import {PartnerHuntWorkspace} from "./PartnerHuntWorkspace";
export const dynamic="force-dynamic";export const metadata={title:"Partner Hunt",robots:{index:false,follow:false}};
const value=(input:string|number|null)=>input===null?"Unknown":String(input);
export default async function PartnerHuntPage(){await requireMarketplaceAdministrator("/admin/marketplace/partners");const profile=chefGringoApplicationProfile();const email=getEmailCaptureHealth();return <main className="partner-hunt"><header><p>Founder-only · local in-memory workflow</p><h1>Partner Hunt</h1><p>Customer value first. Commercial opportunity second. Evidence before verification.</p></header><section className="score-separation" aria-label="Launch health"><article><span>Email capture</span><strong>{email.status}</strong><p>{email.detail} Credentials are never displayed.</p></article><article><span>Analytics persistence</span><strong>DISCONNECTED</strong><p>Canonical browser events dispatch locally; no external collector or durable reporting is configured.</p></article></section><details open><summary>Reusable affiliate application profile</summary><dl><div><dt>Brand</dt><dd>{profile.brandName}</dd></div><div><dt>Website</dt><dd>{value(profile.websiteUrl)}</dd></div><div><dt>Contact</dt><dd>{profile.publicContactEmail}</dd></div><div><dt>Business</dt><dd>{profile.businessDescription}</dd></div><div><dt>Audience</dt><dd>{profile.targetAudience}</dd></div><div><dt>Approach</dt><dd>{profile.recommendationApproach}</dd></div><div><dt>Disclosure</dt><dd>{value(profile.disclosureUrl)}</dd></div><div><dt>Active channels</dt><dd>{profile.promotionalChannels.join(" · ")}</dd></div><div><dt>Traffic / email / social metrics</dt><dd>Unknown / Unknown / Unknown</dd></div></dl></details><section aria-labelledby="priority-board-title"><h2 id="priority-board-title">What should I pursue next?</h2><div className="opportunity-board">{partnerHuntFixtures.map(record=>{const apply=readiness(record,"apply");return <article className="opportunity-card" key={`priority:${record.id}`}><span>{applicationPriority(record)}</span><h3>{record.providerName}</h3><p><strong>Program:</strong> {record.programType}</p><p><strong>Lane:</strong> {record.commercialLane}</p><p><strong>Application/contact route:</strong> {value(record.contactOrApplicationRoute)}</p><p><strong>Evidence:</strong> {record.evidence.length?`${record.evidence.length} item(s)`:"None"}</p><p><strong>Next required action:</strong> {apply.missing[0]??"Founder review before submission"}</p></article>})}</div></section><PartnerHuntWorkspace/></main>}
