import type {D1DatabaseLike} from "./index.ts";

export const OUTBOX_STATES=["draft","awaiting_approval","approved_waiting","sending","published_unverified","verified","failed","cancelled"] as const;
export type OutboxState=typeof OUTBOX_STATES[number];
export type PromotionStatus="unknown"|"allowed"|"blocked";
export type GrowthControlScope="global_outbound"|"organic_publishing"|"paid_publishing"|"dispatcher"|`channel:${"facebook"|"instagram"|"pinterest"|"tiktok"}`;

const CHANNELS=new Set(["facebook","instagram","pinterest","tiktok"]);
const CONTROL_SCOPES=new Set(["global_outbound","organic_publishing","paid_publishing","dispatcher","channel:facebook","channel:instagram","channel:pinterest","channel:tiktok"]);
const TRANSITIONS:Record<OutboxState,readonly OutboxState[]>={
  draft:["awaiting_approval","cancelled"],
  awaiting_approval:["approved_waiting","cancelled"],
  approved_waiting:["sending","cancelled"],
  sending:["published_unverified","failed"],
  published_unverified:["verified","failed"],
  verified:[],failed:[],cancelled:[],
};

export type OutboxRow={id:string;idempotencyKey:string;packageId:string;variantId:string;destinationUrlId:string;partnerId:string|null;channel:string;targetAccount:string;state:OutboxState;publicationKind:"organic"|"paid";copySnapshot:string;copyHash:string;assetRefs:string;trackedHref:string;approvalId:string|null;approvedBy:string|null;approvedAt:string|null;scheduledAt:string|null;attemptCount:number;maxAttempts:number;remotePublicationId:string|null;remotePublicationUrl:string|null;verificationState:string;lastError:string|null;createdBy:string;createdAt:string;updatedAt:string};
const outboxSelect=`SELECT id,idempotency_key AS idempotencyKey,package_id AS packageId,variant_id AS variantId,destination_url_id AS destinationUrlId,partner_id AS partnerId,channel,target_account AS targetAccount,state,publication_kind AS publicationKind,copy_snapshot AS copySnapshot,copy_hash AS copyHash,asset_refs AS assetRefs,tracked_href AS trackedHref,approval_id AS approvalId,approved_by AS approvedBy,approved_at AS approvedAt,scheduled_at AS scheduledAt,attempt_count AS attemptCount,max_attempts AS maxAttempts,remote_publication_id AS remotePublicationId,remote_publication_url AS remotePublicationUrl,verification_state AS verificationState,last_error AS lastError,created_by AS createdBy,created_at AS createdAt,updated_at AS updatedAt FROM publication_outbox`;

function required(value:string,label:string){const text=value.trim();if(!text)throw new Error(`${label} is required.`);return text;}
function changes(result:{meta?:Record<string,unknown>}){return Number(result.meta?.changes??0);}
async function sha256(value:string){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function eventId(){return `goe:${crypto.randomUUID()}`;}
async function audit(db:D1DatabaseLike,outboxId:string,fromState:OutboxState|null,toState:OutboxState,actorEmail:string|null,detail:Record<string,unknown>={}){await db.prepare("INSERT INTO publication_outbox_events (id,outbox_id,from_state,to_state,actor_email,detail,occurred_at) VALUES (?,?,?,?,?,?,?)").bind(eventId(),outboxId,fromState,toState,actorEmail,JSON.stringify(detail),new Date().toISOString()).run();}

export async function getGrowthControls(db:D1DatabaseLike){return (await db.prepare("SELECT scope,enabled,reason,actor_email AS actorEmail,updated_at AS updatedAt FROM growth_os_controls ORDER BY scope").all<{scope:GrowthControlScope;enabled:number;reason:string;actorEmail:string|null;updatedAt:string}>()).results.map(row=>({...row,enabled:Boolean(row.enabled)}));}
export async function setGrowthControl(db:D1DatabaseLike,input:{scope:GrowthControlScope|string;enabled:boolean;reason:string;actorEmail:string}){if(!CONTROL_SCOPES.has(input.scope))throw new Error("Unsupported Growth OS control scope.");if(input.scope==="paid_publishing"&&input.enabled)throw new Error("Paid publishing cannot be enabled during Growth OS Phase 1.");const reason=required(input.reason,"Control change reason");await db.prepare("UPDATE growth_os_controls SET enabled=?,reason=?,actor_email=?,updated_at=CURRENT_TIMESTAMP WHERE scope=?").bind(input.enabled?1:0,reason,input.actorEmail,input.scope).run();return (await getGrowthControls(db)).find(row=>row.scope===input.scope)!;}

export async function setPartnerPublishingPolicy(db:D1DatabaseLike,input:{partnerId:string;organicPromotionStatus:PromotionStatus;paidPromotionStatus:PromotionStatus;affiliateDestinationVerified:boolean;termsSourceUrl?:string|null;termsVerifiedAt?:string|null;trademarkRestrictions?:string;geographicRestrictions?:string;publishingEnabled:boolean;publishingDisabledReason?:string|null}){for(const status of [input.organicPromotionStatus,input.paidPromotionStatus])if(!["unknown","allowed","blocked"].includes(status))throw new Error("Promotion status must be unknown, allowed, or blocked.");if(input.paidPromotionStatus==="allowed")throw new Error("Paid promotion cannot be operationally allowed during Phase 1.");if(input.publishingEnabled&&(input.organicPromotionStatus!=="allowed"||!input.affiliateDestinationVerified||!input.termsVerifiedAt))throw new Error("Partner publishing cannot be enabled without allowed organic terms, a verified affiliate destination, and verified terms timestamp.");if(input.termsVerifiedAt&&Number.isNaN(Date.parse(input.termsVerifiedAt)))throw new Error("Partner terms verification timestamp is invalid.");const result=await db.prepare("UPDATE partner_opportunities SET organic_promotion_status=?,paid_promotion_status=?,affiliate_destination_verified=?,terms_source_url=?,terms_verified_at=?,trademark_restrictions=?,geographic_restrictions=?,publishing_enabled=?,publishing_disabled_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(input.organicPromotionStatus,input.paidPromotionStatus,input.affiliateDestinationVerified?1:0,input.termsSourceUrl??null,input.termsVerifiedAt??null,input.trademarkRestrictions??"unknown",input.geographicRestrictions??"unknown",input.publishingEnabled?1:0,input.publishingDisabledReason??null,input.partnerId).run();if(!changes(result))throw new Error("Partner not found.");return db.prepare("SELECT id,provider_name AS providerName,organic_promotion_status AS organicPromotionStatus,paid_promotion_status AS paidPromotionStatus,affiliate_destination_verified AS affiliateDestinationVerified,terms_source_url AS termsSourceUrl,terms_verified_at AS termsVerifiedAt,trademark_restrictions AS trademarkRestrictions,geographic_restrictions AS geographicRestrictions,publishing_enabled AS publishingEnabled,publishing_disabled_reason AS publishingDisabledReason FROM partner_opportunities WHERE id=?").bind(input.partnerId).first();}

export async function getOutboxEntry(db:D1DatabaseLike,id:string){return db.prepare(`${outboxSelect} WHERE id=?`).bind(id).first<OutboxRow>();}
export async function listOutbox(db:D1DatabaseLike,state?:OutboxState){if(state&&!OUTBOX_STATES.includes(state))throw new Error("Unsupported outbox state.");return (await db.prepare(`${outboxSelect}${state?" WHERE state=?":""} ORDER BY created_at DESC`).bind(...(state?[state]:[])).all<OutboxRow>()).results;}

export async function createOutboxEntry(db:D1DatabaseLike,input:{packageId:string;variantId:string;destinationUrlId:string;channel:string;targetAccount:string;trackedHref:string;createdBy:string;scheduledAt?:string|null;publicationKind?:"organic"|"paid"}){if(!CHANNELS.has(input.channel))throw new Error("Unsupported publication channel.");if(input.publicationKind==="paid")throw new Error("Paid publication jobs are prohibited during Phase 1.");if(input.scheduledAt&&Number.isNaN(Date.parse(input.scheduledAt)))throw new Error("Scheduled timestamp is invalid.");const linked=await db.prepare(`SELECT v.copy AS copySnapshot,v.asset_ids AS assetRefs,v.channel,p.id AS packageId,p.commercial_posture AS commercialPosture,o.partner_opportunity_id AS partnerId,d.href AS trackedHref FROM social_channel_variants v JOIN social_content_packages p ON p.id=v.package_id JOIN social_content_opportunities o ON o.id=p.opportunity_id JOIN social_destination_urls d ON d.id=? AND d.variant_id=v.id AND d.package_id=p.id WHERE v.id=? AND p.id=?`).bind(input.destinationUrlId,input.variantId,input.packageId).first<{copySnapshot:string;assetRefs:string;channel:string;packageId:string;commercialPosture:string;partnerId:string|null;trackedHref:string}>();if(!linked)throw new Error("Outbox package, variant, and destination must refer to one canonical workspace.");if(linked.channel!==input.channel)throw new Error("Outbox channel does not match the variant.");if(linked.trackedHref!==input.trackedHref)throw new Error("Tracked destination does not match the durable destination record.");if(linked.commercialPosture==="pending")throw new Error("Pending commercial posture cannot enter the publication outbox.");if(linked.commercialPosture==="affiliate"){if(!linked.partnerId)throw new Error("Affiliate publication requires a partner registry record.");const partner=await db.prepare("SELECT lifecycle,affiliate_url AS affiliateUrl,organic_promotion_status AS organicStatus,affiliate_destination_verified AS destinationVerified,terms_verified_at AS termsVerifiedAt,publishing_enabled AS publishingEnabled FROM partner_opportunities WHERE id=?").bind(linked.partnerId).first<{lifecycle:string;affiliateUrl:string|null;organicStatus:string;destinationVerified:number;termsVerifiedAt:string|null;publishingEnabled:number}>();if(!partner||partner.lifecycle!=="active"||!partner.affiliateUrl||partner.organicStatus!=="allowed"||!partner.destinationVerified||!partner.termsVerifiedAt||!partner.publishingEnabled)throw new Error("Affiliate publication fails closed until the partner is active, terms-verified, destination-verified, and explicitly enabled.");}
 const copyHash=await sha256(linked.copySnapshot);const idempotencyKey=await sha256([input.packageId,input.variantId,input.destinationUrlId,input.channel,input.targetAccount,copyHash].join("|"));const existing=await db.prepare(`${outboxSelect} WHERE idempotency_key=?`).bind(idempotencyKey).first<OutboxRow>();if(existing)return existing;const id=`outbox:${crypto.randomUUID()}`;await db.prepare("INSERT INTO publication_outbox (id,idempotency_key,package_id,variant_id,destination_url_id,partner_id,channel,target_account,state,publication_kind,copy_snapshot,copy_hash,asset_refs,tracked_href,scheduled_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,idempotencyKey,input.packageId,input.variantId,input.destinationUrlId,linked.partnerId,input.channel,required(input.targetAccount,"Target account"),"awaiting_approval","organic",linked.copySnapshot,copyHash,linked.assetRefs,input.trackedHref,input.scheduledAt??null,input.createdBy).run();await audit(db,id,null,"awaiting_approval",input.createdBy,{idempotencyKey});return (await getOutboxEntry(db,id))!;}

export async function approveOutboxEntry(db:D1DatabaseLike,id:string,actorEmail:string){const row=await getOutboxEntry(db,id);if(!row)throw new Error("Outbox entry not found.");if(row.state!=="awaiting_approval")throw new Error("Only an awaiting-approval outbox entry can be approved.");const approval=await db.prepare("SELECT id,actor_email AS actorEmail,occurred_at AS occurredAt FROM social_approvals WHERE decision='approved' AND ((subject_kind='variant' AND subject_id=?) OR (subject_kind='package' AND subject_id=?)) ORDER BY occurred_at DESC LIMIT 1").bind(row.variantId,row.packageId).first<{id:string;actorEmail:string;occurredAt:string}>();if(!approval)throw new Error("A durable package or variant approval is required before the outbox can advance.");const now=new Date().toISOString();const result=await db.prepare("UPDATE publication_outbox SET state='approved_waiting',approval_id=?,approved_by=?,approved_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='awaiting_approval'").bind(approval.id,actorEmail,now,id).run();if(!changes(result))throw new Error("Outbox state changed concurrently; approval was not applied.");await audit(db,id,"awaiting_approval","approved_waiting",actorEmail,{approvalId:approval.id});return (await getOutboxEntry(db,id))!;}

export async function transitionOutboxEntry(db:D1DatabaseLike,input:{id:string;toState:OutboxState;actorEmail:string;detail?:Record<string,unknown>}){const row=await getOutboxEntry(db,input.id);if(!row)throw new Error("Outbox entry not found.");if(!OUTBOX_STATES.includes(input.toState)||!TRANSITIONS[row.state].includes(input.toState))throw new Error(`Invalid outbox transition ${row.state} -> ${input.toState}.`);if(input.toState==="sending"){const controls=await getGrowthControls(db);const enabled=(scope:string)=>controls.find(control=>control.scope===scope)?.enabled===true;if(!enabled("global_outbound")||!enabled("organic_publishing")||!enabled("dispatcher")||!enabled(`channel:${row.channel}`))throw new Error("Outbound dispatch is disabled by a Growth OS kill switch.");if(row.publicationKind!=="organic")throw new Error("Phase 1 dispatcher cannot send paid publication jobs.");}
 const result=await db.prepare("UPDATE publication_outbox SET state=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state=?").bind(input.toState,input.id,row.state).run();if(!changes(result))throw new Error("Outbox state changed concurrently; transition was not applied.");await audit(db,input.id,row.state,input.toState,input.actorEmail,input.detail);return (await getOutboxEntry(db,input.id))!;}
