import type {D1DatabaseLike} from "./index.ts";
import {getGrowthControls,getOutboxEntry,type OutboxRow} from "./growth-os-repository.ts";

export type DispatchEnvelope={version:1;outboxId:string;idempotencyKey:string;attemptNumber:number;channel:string;targetAccount:string;copy:string;copyHash:string;assetRefs:string[];trackedHref:string;scheduledAt:string|null};
export type DispatchTransportResult={status:"accepted"|"ambiguous"|"failed";responseCode?:number|null;remotePublicationId?:string|null;remotePublicationUrl?:string|null;error?:string|null};
export type VerificationReceipt={outboxId:string;leaseToken:string;status:"published"|"verified"|"failed"|"ambiguous";remotePublicationId?:string|null;remotePublicationUrl?:string|null;observedChannel?:string|null;observedTargetAccount?:string|null;observedCopyHash?:string|null;error?:string|null};

function changes(result:{meta?:Record<string,unknown>}){return Number(result.meta?.changes??0);}
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function stableEnvelopeBody(envelope:DispatchEnvelope){return JSON.stringify(envelope);}
async function hmac(secret:string,body:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const signature=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(body));return [...new Uint8Array(signature)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function parseAssets(value:string){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed.map(String):[]}catch{return []}}
async function assertDispatchEnabled(db:D1DatabaseLike,row:OutboxRow){const controls=await getGrowthControls(db);const enabled=(scope:string)=>controls.find(item=>item.scope===scope)?.enabled===true;if(!enabled("global_outbound")||!enabled("organic_publishing")||!enabled("dispatcher")||!enabled(`channel:${row.channel}`))throw new Error("Outbound dispatch is disabled by a Growth OS kill switch.");if(row.publicationKind!=="organic")throw new Error("Phase 1 dispatcher cannot send paid publication jobs.");}

export async function claimDispatchAttempt(db:D1DatabaseLike,input:{outboxId:string;adapter:string}){const row=await getOutboxEntry(db,input.outboxId);if(!row)throw new Error("Outbox entry not found.");if(row.state!=="approved_waiting")throw new Error("Only approved-waiting jobs can be claimed for dispatch.");await assertDispatchEnabled(db,row);if(row.attemptCount>=row.maxAttempts)throw new Error("Dispatch attempt limit reached.");const attemptNumber=row.attemptCount+1;const leaseToken=crypto.randomUUID();const envelope:DispatchEnvelope={version:1,outboxId:row.id,idempotencyKey:row.idempotencyKey,attemptNumber,channel:row.channel,targetAccount:row.targetAccount,copy:row.copySnapshot,copyHash:row.copyHash,assetRefs:parseAssets(row.assetRefs),trackedHref:row.trackedHref,scheduledAt:row.scheduledAt};const envelopeHash=await sha256(stableEnvelopeBody(envelope));const transition=await db.prepare("UPDATE publication_outbox SET state='sending',attempt_count=?,verification_state='pending',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='approved_waiting' AND attempt_count=?").bind(attemptNumber,row.id,row.attemptCount).run();if(!changes(transition))throw new Error("Outbox state changed concurrently; dispatcher claim was not acquired.");await db.prepare("INSERT INTO publication_dispatch_attempts (id,outbox_id,attempt_number,lease_token,adapter,envelope_hash,status) VALUES (?,?,?,?,?,?, 'claimed')").bind(`dispatch:${crypto.randomUUID()}`,row.id,attemptNumber,leaseToken,input.adapter,envelopeHash).run();return {envelope,leaseToken,envelopeHash};}

export async function signDispatchEnvelope(envelope:DispatchEnvelope,secret:string){if(!secret.trim())throw new Error("Dispatcher signing secret is not configured.");const body=stableEnvelopeBody(envelope);return {body,signature:await hmac(secret,body),algorithm:"hmac-sha256" as const};}
export async function verifySignedBody(body:string,signature:string,secret:string){if(!secret.trim()||!signature.trim())return false;const expected=await hmac(secret,body);if(expected.length!==signature.length)return false;let mismatch=0;for(let i=0;i<expected.length;i++)mismatch|=expected.charCodeAt(i)^signature.charCodeAt(i);return mismatch===0;}

export async function recordDispatchTransportResult(db:D1DatabaseLike,input:{outboxId:string;leaseToken:string;result:DispatchTransportResult}){const attempt=await db.prepare("SELECT id,status FROM publication_dispatch_attempts WHERE outbox_id=? AND lease_token=? ORDER BY attempt_number DESC LIMIT 1").bind(input.outboxId,input.leaseToken).first<{id:string;status:string}>();if(!attempt)throw new Error("Dispatch lease was not found.");if(attempt.status!=="claimed")throw new Error("Dispatch lease has already been resolved.");const row=await getOutboxEntry(db,input.outboxId);if(!row||row.state!=="sending")throw new Error("Outbox job is not in sending state.");const r=input.result;if(r.status==="failed"){await db.batch([db.prepare("UPDATE publication_dispatch_attempts SET status='failed',response_code=?,error=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='claimed'").bind(r.responseCode??null,r.error??"Transport failed",attempt.id),db.prepare("UPDATE publication_outbox SET state='failed',verification_state='failed',last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='sending'").bind(r.error??"Transport failed",row.id)]);return (await getOutboxEntry(db,row.id))!;}
+const status=r.status==="accepted"?"accepted":"ambiguous";const verification=r.status==="accepted"?"pending":"ambiguous";await db.batch([db.prepare("UPDATE publication_dispatch_attempts SET status=?,response_code=?,remote_publication_id=?,remote_publication_url=?,error=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='claimed'").bind(status,r.responseCode??null,r.remotePublicationId??null,r.remotePublicationUrl??null,r.error??null,attempt.id),db.prepare("UPDATE publication_outbox SET state='published_unverified',verification_state=?,remote_publication_id=?,remote_publication_url=?,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='sending'").bind(verification,r.remotePublicationId??null,r.remotePublicationUrl??null,r.error??null,row.id)]);return (await getOutboxEntry(db,row.id))!;}

export async function applyVerificationReceipt(db:D1DatabaseLike,receipt:VerificationReceipt){const attempt=await db.prepare("SELECT id,status FROM publication_dispatch_attempts WHERE outbox_id=? AND lease_token=? ORDER BY attempt_number DESC LIMIT 1").bind(receipt.outboxId,receipt.leaseToken).first<{id:string;status:string}>();if(!attempt)throw new Error("Verification lease was not found.");const row=await getOutboxEntry(db,receipt.outboxId);if(!row)throw new Error("Outbox entry not found.");if(row.state!=="published_unverified")throw new Error("Only published-unverified jobs can accept verification receipts.");const remoteId=receipt.remotePublicationId??row.remotePublicationId;const remoteUrl=receipt.remotePublicationUrl??row.remotePublicationUrl;if(receipt.status==="verified"){const match=receipt.observedChannel===row.channel&&receipt.observedTargetAccount===row.targetAccount&&receipt.observedCopyHash===row.copyHash&&Boolean(remoteId)&&Boolean(remoteUrl);if(!match){await db.prepare("UPDATE publication_outbox SET verification_state='ambiguous',last_error='Verification receipt did not match expected channel, account, copy hash, or remote identity.',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id).run();throw new Error("Verification receipt did not match the expected publication identity.");}await db.batch([db.prepare("UPDATE publication_dispatch_attempts SET status='verified',remote_publication_id=?,remote_publication_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(remoteId,remoteUrl,attempt.id),db.prepare("UPDATE publication_outbox SET state='verified',verification_state='verified',remote_publication_id=?,remote_publication_url=?,last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='published_unverified'").bind(remoteId,remoteUrl,row.id)]);return (await getOutboxEntry(db,row.id))!;}
+if(receipt.status==="failed"){await db.batch([db.prepare("UPDATE publication_dispatch_attempts SET status='failed',error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(receipt.error??"Verification failed",attempt.id),db.prepare("UPDATE publication_outbox SET state='failed',verification_state='failed',last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='published_unverified'").bind(receipt.error??"Verification failed",row.id)]);return (await getOutboxEntry(db,row.id))!;}
+await db.prepare("UPDATE publication_outbox SET verification_state='ambiguous',remote_publication_id=?,remote_publication_url=?,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(remoteId??null,remoteUrl??null,receipt.error??(receipt.status==="ambiguous"?"Remote state is ambiguous.":null),row.id).run();return (await getOutboxEntry(db,row.id))!;}
