import type { CulinaryDomain } from "./source-policy.ts";

export const CORPUS_MANIFEST_VERSION = "10.0.0";
export const CORPUS_ACTIVATED_AT = "2026-08-21";

export const PRODUCTION_ELIGIBILITIES = ["public", "limited", "unavailable", "rejected"] as const;
export type ProductionEligibility = typeof PRODUCTION_ELIGIBILITIES[number];

export type ManifestEntry = {
  id: string;
  intendedClaims: string[];
  evidenceDomain: CulinaryDomain;
  issuingOrganization: string;
  canonicalUrl: string | null;
  jurisdiction: string | null;
  authorityTier: 1 | 2 | 3;
  expectedContentType: string;
  expectedPublicationDate: string | null;
  reviewNotes: string;
  licensingNotes: string;
  refreshIntervalDays: number;
  productionEligibility: ProductionEligibility;
  reasonForInclusion: string;
  fixtureId: string | null;
  unavailableReason: string | null;
};

export const AUTHORITATIVE_MANIFEST: ManifestEntry[] = [
  {
    id: "corpus:usda-fsis-safe-temps",
    intendedClaims: ["Ground beef 160°F", "Poultry 165°F", "Fish 145°F"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "USDA Food Safety and Inspection Service",
    canonicalUrl: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/safe-temperature-chart",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Live HTTPS GET returned Akamai 403 in this environment. Activated from a short U.S. government-work excerpt ingested through Stage 9.",
    licensingNotes: "U.S. government work. Short excerpt for citation. Full chart remains at the canonical URL.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Highest-value food-safety operational chart for protein cookery.",
    fixtureId: "usda-fsis-safe-temps",
    unavailableReason: null,
  },
  {
    id: "corpus:usda-fsis-thawing",
    intendedClaims: ["Do not thaw meat on the counter", "Refrigerator, cold water, or microwave thawing"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "USDA Food Safety and Inspection Service",
    canonicalUrl: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/the-big-thaw-safe-defrosting-methods",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Same 403 barrier as other FSIS pages. Excerpt is official thawing methods only.",
    licensingNotes: "U.S. government work. Short excerpt for citation.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Counter-thawing is a common, high-risk home mistake.",
    fixtureId: "usda-fsis-thawing",
    unavailableReason: null,
  },
  {
    id: "corpus:usda-fsis-danger-zone",
    intendedClaims: ["Danger zone 40–140°F", "Perishable leftovers within 2 hours"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "USDA Food Safety and Inspection Service",
    canonicalUrl: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/danger-zone",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Live FSIS GET 403. Excerpt covers leftover time, not the FDA Food Code active-cooling process.",
    licensingNotes: "U.S. government work. Short excerpt for citation.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Separates leftover sit-time from Food Code cooling steps so the two are not silently merged.",
    fixtureId: "usda-fsis-danger-zone",
    unavailableReason: null,
  },
  {
    id: "corpus:fda-food-code-tcs",
    intendedClaims: ["TCS cold hold 41°F", "Hot hold 135°F", "Cool 135→70 in 2 hours then to 41 in 4 more"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "U.S. Food and Drug Administration",
    canonicalUrl: "https://www.fda.gov/food/fda-food-code/food-code-2022",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "application/pdf",
    expectedPublicationDate: "2022",
    reviewNotes: "Full Food Code PDF is not parsed. Short TCS time/temperature facts only. Not a substitute for the adopted local code.",
    licensingNotes: "U.S. government work. Short excerpt. Full Food Code remains at the canonical URL.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Operational time/temperature control for foodservice.",
    fixtureId: "fda-food-code-tcs",
    unavailableReason: null,
  },
  {
    id: "corpus:fda-major-allergens",
    intendedClaims: ["Nine major food allergens including sesame"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "U.S. Food and Drug Administration",
    canonicalUrl: "https://www.fda.gov/food/food-allergensgluten-free-guidance-documents-regulatory-information/food-allergies",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "HEAD to FDA html was 200; full page was not stored. Short official allergen list only.",
    licensingNotes: "U.S. government work. Short excerpt for citation.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Allergen cross-contact is a high-consequence kitchen control.",
    fixtureId: "fda-major-allergens",
    unavailableReason: null,
  },
  {
    id: "corpus:cdc-four-steps",
    intendedClaims: ["Clean, Separate, Cook, Chill"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "Centers for Disease Control and Prevention",
    canonicalUrl: "https://www.cdc.gov/food-safety/prevention/index.html",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Live CDC GET returned Akamai 403. Four-step prevention excerpt only.",
    licensingNotes: "U.S. government work. Short excerpt for citation.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Cross-contamination and cleaning vs cooking controls.",
    fixtureId: "cdc-four-steps",
    unavailableReason: null,
  },
  {
    id: "corpus:fda-cleaning-sanitizing",
    intendedClaims: ["Cleaning removes soil", "Sanitizing reduces pathogens on a cleaned surface"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "U.S. Food and Drug Administration",
    canonicalUrl: "https://www.fda.gov/food/retail-food-protection/fda-food-code",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: "2022",
    reviewNotes: "Definitional Food Code distinction. Not a chemical concentration chart.",
    licensingNotes: "U.S. government work. Short excerpt.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Operators routinely conflate cleaning and sanitizing.",
    fixtureId: "fda-cleaning-sanitizing",
    unavailableReason: null,
  },
  {
    id: "corpus:usda-fooddata-central",
    intendedClaims: ["FoodData Central is USDA’s nutrient database", "It is not a meal prescription"],
    evidenceDomain: "nutrition_therapeutic_diets",
    issuingOrganization: "USDA Agricultural Research Service",
    canonicalUrl: "https://fdc.nal.usda.gov/",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Orientation only. No nutrient values were copied from the database.",
    licensingNotes: "U.S. government work. Short excerpt.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Points nutrition questions at the official database instead of invented numbers.",
    fixtureId: "usda-fooddata-central",
    unavailableReason: null,
  },
  {
    id: "corpus:dietary-guidelines-2020",
    intendedClaims: ["Dietary Guidelines 2020–2025 are HHS/USDA policy", "Not a clinical prescription"],
    evidenceDomain: "nutrition_therapeutic_diets",
    issuingOrganization: "U.S. Department of Agriculture and U.S. Department of Health and Human Services",
    canonicalUrl: "https://www.dietaryguidelines.gov/sites/default/files/2021-03/Dietary_Guidelines_for_Americans-2020-2025.pdf",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "application/pdf",
    expectedPublicationDate: "2020",
    reviewNotes: "Full PDF not parsed. Identity and role of the Guidelines only.",
    licensingNotes: "U.S. government work. Short excerpt. Full PDF remains at the canonical URL.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Official nutrition policy orientation without prescribing diets.",
    fixtureId: "dietary-guidelines-2020",
    unavailableReason: null,
  },
  {
    id: "corpus:fda-nutrition-facts",
    intendedClaims: ["Nutrition Facts label is FDA-regulated", "Use the label; do not invent %DV"],
    evidenceDomain: "nutrition_therapeutic_diets",
    issuingOrganization: "U.S. Food and Drug Administration",
    canonicalUrl: "https://www.fda.gov/food/nutrition-facts-label/how-understand-and-use-nutrition-facts-label",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Label-reading orientation, not a nutrient table.",
    licensingNotes: "U.S. government work. Short excerpt.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Stops invented nutrition math.",
    fixtureId: "fda-nutrition-facts",
    unavailableReason: null,
  },
  {
    id: "corpus:iddsi-level-5",
    intendedClaims: ["IDDSI Level 5 is minced and moist", "Adult particle size 4 mm", "Not a substitute for clinical assessment"],
    evidenceDomain: "nutrition_therapeutic_diets",
    issuingOrganization: "International Dysphagia Diet Standardisation Initiative",
    canonicalUrl: "https://www.iddsi.org/framework/",
    jurisdiction: null,
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Short official descriptor with attribution. Chef Gringo does not prescribe texture diets.",
    licensingNotes: "IDDSI framework is used under IDDSI terms; short descriptor plus link. Not the full testing methods PDF.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Healthcare dining already uses IDDSI in this repository; public answers must stay non-prescriptive.",
    fixtureId: "iddsi-level-5",
    unavailableReason: null,
  },
  {
    id: "corpus:iddsi-level-4",
    intendedClaims: ["IDDSI Level 4 is pureed", "No lumps", "Falls off the spoon in a coherent bolus"],
    evidenceDomain: "nutrition_therapeutic_diets",
    issuingOrganization: "International Dysphagia Diet Standardisation Initiative",
    canonicalUrl: "https://www.iddsi.org/framework/",
    jurisdiction: null,
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Pairs with the unpublished IDDSI knowledge-core pilot. Limited public exposure.",
    licensingNotes: "Short official descriptor plus link. Not the full framework PDF.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Texture-modification questions are already in the product; they need official naming without clinical orders.",
    fixtureId: "iddsi-level-4",
    unavailableReason: null,
  },
  {
    id: "corpus:florida-dbpr-hotels-restaurants",
    intendedClaims: ["Florida public food service is licensed by DBPR Division of Hotels and Restaurants"],
    evidenceDomain: "business_licensing",
    issuingOrganization: "Florida Department of Business and Professional Regulation",
    canonicalUrl: "https://www.myfloridalicense.com/DBPR/hotels-restaurants/",
    jurisdiction: "Florida",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "HEAD redirected 302 to https://www2.myfloridalicense.com/hotels-restaurants/. Agency identity excerpt only. Statute and fees not retrieved.",
    licensingNotes: "Official agency landing identity. Not statute text.",
    refreshIntervalDays: 90,
    productionEligibility: "public",
    reasonForInclusion: "Names the correct Florida restaurant regulator.",
    fixtureId: "florida-dbpr-hotels-restaurants",
    unavailableReason: null,
  },
  {
    id: "corpus:florida-cottage-food",
    intendedClaims: ["Florida cottage food is an FDACS program", "It is not a DBPR restaurant license"],
    evidenceDomain: "business_licensing",
    issuingOrganization: "Florida Department of Agriculture and Consumer Services",
    canonicalUrl: "https://www.fdacs.gov/Business-Services/Food-Establishment-Inspections/Cottage-Food-Operations",
    jurisdiction: "Florida",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Program identity and boundary only. Current sales caps and label rules were not retrieved live.",
    licensingNotes: "Official agency program identity. Confirm current limits on the FDACS page.",
    refreshIntervalDays: 90,
    productionEligibility: "public",
    reasonForInclusion: "Home bakers are routinely sent to the wrong agency.",
    fixtureId: "florida-cottage-food",
    unavailableReason: null,
  },
  {
    id: "corpus:florida-dor-sales-tax",
    intendedClaims: ["Selling taxable goods in Florida generally requires DOR sales-tax registration"],
    evidenceDomain: "business_licensing",
    issuingOrganization: "Florida Department of Revenue",
    canonicalUrl: "https://floridarevenue.com/taxes/taxesfees/Pages/sales_tax.aspx",
    jurisdiction: "Florida",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Orientation only. Rate tables and exemptions were not retrieved.",
    licensingNotes: "Official agency orientation. Not a tax opinion.",
    refreshIntervalDays: 90,
    productionEligibility: "public",
    reasonForInclusion: "Licensing and tax registration are different Florida obligations.",
    fixtureId: "florida-dor-sales-tax",
    unavailableReason: null,
  },
  {
    id: "corpus:sarasota-county-food",
    intendedClaims: [],
    evidenceDomain: "business_licensing",
    issuingOrganization: "Sarasota County",
    canonicalUrl: "https://www.scgov.net/",
    jurisdiction: "Sarasota County, Florida",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "County-specific food rules were not retrieved. Statewide DBPR/FDACS answers must not be generalized as Sarasota County law.",
    licensingNotes: "Not ingested.",
    refreshIntervalDays: 90,
    productionEligibility: "unavailable",
    reasonForInclusion: "Makes the county gap visible instead of filling it with statewide copy.",
    fixtureId: null,
    unavailableReason: "Live county ordinance text was not retrieved; jurisdiction must stay explicit.",
  },
  {
    id: "corpus:practice-mirepoix",
    intendedClaims: ["Mirepoix is onion, carrot, and celery, typically 2:1:1"],
    evidenceDomain: "culinary_technique",
    issuingOrganization: "Chef Gringo",
    canonicalUrl: null,
    jurisdiction: null,
    authorityTier: 2,
    expectedContentType: "text/plain",
    expectedPublicationDate: "2026-08-21",
    reviewNotes: "Primary culinary-practice note authored by Chef Gringo. Labeled practice, not external authority.",
    licensingNotes: "Chef Gringo original practice note.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "High-frequency definitional question already answered correctly without retrieval.",
    fixtureId: "practice-mirepoix",
    unavailableReason: null,
  },
  {
    id: "corpus:practice-emulsion",
    intendedClaims: ["Emulsions break when fat and water separate", "Re-emulsify off heat with a little water or by whisking in a fresh yolk/mustard binder"],
    evidenceDomain: "culinary_technique",
    issuingOrganization: "Chef Gringo",
    canonicalUrl: null,
    jurisdiction: null,
    authorityTier: 2,
    expectedContentType: "text/plain",
    expectedPublicationDate: "2026-08-21",
    reviewNotes: "Practice, not a journal article.",
    licensingNotes: "Chef Gringo original practice note.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Broken-sauce questions are common and do not need live search.",
    fixtureId: "practice-emulsion",
    unavailableReason: null,
  },
  {
    id: "corpus:practice-stock-sauce",
    intendedClaims: ["White stock starts with pale bones and mirepoix", "Brown stock browns bones and vegetables first"],
    evidenceDomain: "culinary_technique",
    issuingOrganization: "Chef Gringo",
    canonicalUrl: null,
    jurisdiction: null,
    authorityTier: 2,
    expectedContentType: "text/plain",
    expectedPublicationDate: "2026-08-21",
    reviewNotes: "Practice covering stocks, roasting, and braising at a definitional level.",
    licensingNotes: "Chef Gringo original practice note.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Core culinary technique coverage without scraping cookbooks.",
    fixtureId: "practice-stock-sauce",
    unavailableReason: null,
  },
  {
    id: "corpus:practice-yield-cost",
    intendedClaims: ["Food-cost % = food cost / food sales", "EP yield = edible portion / as-purchased", "No current industry benchmark is on file"],
    evidenceDomain: "commercial_claims",
    issuingOrganization: "Chef Gringo",
    canonicalUrl: null,
    jurisdiction: null,
    authorityTier: 2,
    expectedContentType: "text/plain",
    expectedPublicationDate: "2026-08-21",
    reviewNotes: "Established calculation methods only. No invented NRA or regional benchmarks.",
    licensingNotes: "Chef Gringo original methods note.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Operators ask for formulas; invented averages would be dishonest.",
    fixtureId: "practice-yield-cost",
    unavailableReason: null,
  },
  {
    id: "corpus:thermoworks-thermapen-one",
    intendedClaims: ["Thermapen ONE stated response 1 second", "Stated accuracy ±0.5°F from -4 to 248°F", "IP67"],
    evidenceDomain: "equipment",
    issuingOrganization: "ThermoWorks",
    canonicalUrl: "https://www.thermoworks.com/products/thermapen-one",
    jurisdiction: null,
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Manufacturer marketing HTML is copyrighted and was not stored in full. Exact-model specs copied from the Chef Gringo catalog record of the manufacturer page.",
    licensingNotes: "Short specification excerpt for citation. Full page remains at the manufacturer URL. Not a live 2026 fetch of the storefront.",
    refreshIntervalDays: 90,
    productionEligibility: "public",
    reasonForInclusion: "Exact-model thermometer already in the Marketplace catalog.",
    fixtureId: "thermoworks-thermapen-one",
    unavailableReason: null,
  },
  {
    id: "corpus:comark-pdt300-datasheet",
    intendedClaims: ["PDT300 6-second response", "Field recalibratable"],
    evidenceDomain: "equipment",
    issuingOrganization: "Comark",
    canonicalUrl: "https://www.comarkinstruments.net/wp-content/uploads/2017/04/20541-1-PDT300-datasheet-USA.pdf",
    jurisdiction: null,
    authorityTier: 1,
    expectedContentType: "application/pdf",
    expectedPublicationDate: "2017",
    reviewNotes: "Binary PDF parser is not enabled. Catalog specs exist but the manufacturer sheet was not transcribed in this stage.",
    licensingNotes: "Manufacturer PDF not stored.",
    refreshIntervalDays: 180,
    productionEligibility: "unavailable",
    reasonForInclusion: "Exact-model datasheet is the preferred equipment source.",
    fixtureId: null,
    unavailableReason: "PDF extraction requires a human transcription; binary parser is not enabled.",
  },
  {
    id: "corpus:waring-wsb50-spec",
    intendedClaims: ["WSB50 12-inch shaft", "750 watts", "ETL/NSF"],
    evidenceDomain: "equipment",
    issuingOrganization: "Waring",
    canonicalUrl: "https://www.waring.com/on/demandware.static/-/Sites-waring-master/default/dwd8f34315/pdf/specSheet/wsb50-big-stik-immersion-blender-spec-sheet-090921%5B1%5D.pdf",
    jurisdiction: null,
    authorityTier: 1,
    expectedContentType: "application/pdf",
    expectedPublicationDate: "2021",
    reviewNotes: "Manufacturer spec sheet is PDF. Catalog-backed short excerpt only.",
    licensingNotes: "Short specification excerpt from the catalog record of the manufacturer sheet. Full PDF not stored.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Representative cooking/production tool already in catalog.",
    fixtureId: "waring-wsb50-spec",
    unavailableReason: null,
  },
  {
    id: "corpus:globe-sp20",
    intendedClaims: ["Globe SP20 is a 20-quart gear-driven mixer", "Published speeds 104/194/353 RPM"],
    evidenceDomain: "equipment",
    issuingOrganization: "Globe Food Equipment",
    canonicalUrl: "https://globefoodequip.com/products/mixers/bench-mixers/sp20.html",
    jurisdiction: null,
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Catalog-backed exact-model excerpt. Page body not live-fetched.",
    licensingNotes: "Short specification excerpt. Full page remains at the manufacturer URL.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Representative mixer already in catalog.",
    fixtureId: "globe-sp20",
    unavailableReason: null,
  },
  {
    id: "corpus:hobart-hl200",
    intendedClaims: ["Hobart Legacy+ HL200 is a 20-quart mixer", "Triple interlock", "189 lb less bowl"],
    evidenceDomain: "equipment",
    issuingOrganization: "Hobart",
    canonicalUrl: "https://www.hobartcorp.com/products/food-prep/mixers/legacy-plus-countertop-mixer",
    jurisdiction: null,
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Catalog-backed exact-model excerpt, not a live manual fetch.",
    licensingNotes: "Short specification excerpt. Full page remains at the manufacturer URL.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "High-consequence institutional mixer already in catalog.",
    fixtureId: "hobart-hl200",
    unavailableReason: null,
  },
  {
    id: "corpus:osha-restaurant-young-workers",
    intendedClaims: ["Restaurant work has recognized slip, burn, and cut hazards", "OSHA does not replace a workplace safety program"],
    evidenceDomain: "equipment",
    issuingOrganization: "Occupational Safety and Health Administration",
    canonicalUrl: "https://www.osha.gov/youth/restaurant",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Hazard orientation only. Not lockout/tagout procedure text.",
    licensingNotes: "U.S. government work. Short excerpt.",
    refreshIntervalDays: 365,
    productionEligibility: "public",
    reasonForInclusion: "Equipment replacement and live-electrical questions need an official workplace-risk boundary.",
    fixtureId: "osha-restaurant",
    unavailableReason: null,
  },
  {
    id: "corpus:fda-seafood-raw",
    intendedClaims: ["Raw shellfish and undercooked seafood carry pathogen risk", "High-risk diners should avoid raw shellfish"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "U.S. Food and Drug Administration",
    canonicalUrl: "https://www.fda.gov/food/buy-store-serve-safe-food/selecting-and-serving-fresh-and-frozen-seafood-safely",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Operational seafood safety, not a harvest-area chart.",
    licensingNotes: "U.S. government work. Short excerpt.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Seafood and shellfish are a requested FDA domain.",
    fixtureId: "fda-seafood",
    unavailableReason: null,
  },
  {
    id: "corpus:fda-egg-safety",
    intendedClaims: ["Cook eggs until yolks and whites are firm unless pasteurized eggs are used for recipes served undercooked"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "U.S. Food and Drug Administration",
    canonicalUrl: "https://www.fda.gov/food/buy-store-serve-safe-food/what-you-need-know-about-egg-safety",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Egg-safety orientation. Not a Farm-to-Table traceback protocol.",
    licensingNotes: "U.S. government work. Short excerpt.",
    refreshIntervalDays: 180,
    productionEligibility: "public",
    reasonForInclusion: "Egg cookery is a daily operational risk.",
    fixtureId: "fda-egg-safety",
    unavailableReason: null,
  },
  {
    id: "corpus:nih-ods-orientation",
    intendedClaims: [],
    evidenceDomain: "nutrition_therapeutic_diets",
    issuingOrganization: "National Institutes of Health Office of Dietary Supplements",
    canonicalUrl: "https://ods.od.nih.gov/",
    jurisdiction: "United States",
    authorityTier: 1,
    expectedContentType: "text/html",
    expectedPublicationDate: null,
    reviewNotes: "Fact sheets were not retrieved. Nutrition answers must not invent supplement doses.",
    licensingNotes: "Not ingested.",
    refreshIntervalDays: 365,
    productionEligibility: "unavailable",
    reasonForInclusion: "Identifies the official clinical-nutrition library without pretending it is loaded.",
    fixtureId: null,
    unavailableReason: "NIH ODS fact sheets were not fetched; Chef Gringo will not invent supplement or micronutrient doses.",
  },
  {
    id: "corpus:thermapen-one-pdf-manual",
    intendedClaims: [],
    evidenceDomain: "equipment",
    issuingOrganization: "ThermoWorks",
    canonicalUrl: "https://www.thermoworks.com/products/thermapen-one",
    jurisdiction: null,
    authorityTier: 1,
    expectedContentType: "application/pdf",
    expectedPublicationDate: null,
    reviewNotes: "A separate official PDF manual was not isolated from the copyrighted storefront HTML.",
    licensingNotes: "Full manual not stored.",
    refreshIntervalDays: 90,
    productionEligibility: "unavailable",
    reasonForInclusion: "Exact manual is preferred over marketing copy when both exist.",
    fixtureId: null,
    unavailableReason: "Official PDF manual was not isolated; catalog specification excerpt is used instead of ingesting the storefront.",
  },
  {
    id: "corpus:stale-cold-hold-45f",
    intendedClaims: ["Cold hold 45°F"],
    evidenceDomain: "food_safety_public_health",
    issuingOrganization: "Example withdrawn local note",
    canonicalUrl: null,
    jurisdiction: "United States",
    authorityTier: 3,
    expectedContentType: "text/plain",
    expectedPublicationDate: "2012-01-01",
    reviewNotes: "Negative fixture. Must remain stale and out of public answers so 41°F FDA guidance is not merged with 45°F.",
    licensingNotes: "Test/internal fixture.",
    refreshIntervalDays: 30,
    productionEligibility: "rejected",
    reasonForInclusion: "Contradiction and freshness handling.",
    fixtureId: "stale-cold-hold-45f",
    unavailableReason: null,
  },
];

export function validateManifest(entries: ManifestEntry[] = AUTHORITATIVE_MANIFEST) {
  const ids = new Set<string>();
  const errors: string[] = [];
  for (const entry of entries) {
    if (!entry.id.startsWith("corpus:")) errors.push(`${entry.id}: id must use corpus: prefix`);
    if (ids.has(entry.id)) errors.push(`${entry.id}: duplicate id`);
    ids.add(entry.id);
    if (!entry.issuingOrganization) errors.push(`${entry.id}: missing organization`);
    if (!PRODUCTION_ELIGIBILITIES.includes(entry.productionEligibility)) errors.push(`${entry.id}: bad eligibility`);
    if (entry.productionEligibility === "unavailable" && !entry.unavailableReason) errors.push(`${entry.id}: unavailable needs a reason`);
    if (entry.productionEligibility === "public" && !entry.fixtureId) errors.push(`${entry.id}: public eligibility requires a fixture`);
    if (entry.canonicalUrl && !entry.canonicalUrl.startsWith("https://") && !entry.canonicalUrl.includes("example.invalid")) {
      errors.push(`${entry.id}: canonical URL must be https`);
    }
    if (entry.authorityTier === 1 && /blog|affiliate|amazon\.com/i.test(entry.canonicalUrl ?? "")) {
      errors.push(`${entry.id}: retailer/affiliate URL cannot be tier 1`);
    }
  }
  return { ok: errors.length === 0, errors, size: entries.length };
}
