import type { ResearchEvidenceItem } from "./evidence.ts";

/**
 * Small, high-quality demonstration set. Every production-exposed item has a
 * real organization and URL already used or documented in this repository.
 * Dates, authors, and quotations are not invented. Test-only fixtures use
 * `.invalid` hosts and must not be exposed as production evidence.
 */

const CATALOGUED_AT = "2026-08-21T00:00:00.000Z";

export const PRODUCTION_EVIDENCE: ResearchEvidenceItem[] = [
  {
    id: "evidence:practice:mirepoix",
    title: "Mirepoix as standard culinary practice",
    sourceOrganization: "Chef Gringo professional practice",
    sourceUrl: null,
    sourceType: "professional_practice",
    authorityTier: 2,
    domain: "culinary_technique",
    publicationDate: null,
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: "Mirepoix is a flavor base of onion, carrot, and celery, commonly two parts onion to one part each carrot and celery.",
    claimContradicted: null,
    excerpt: null,
    locator: "Chef Gringo culinary-practice note",
    validationStatus: "relevant",
    originalValidationStatus: "relevant",
    freshnessStatus: "current",
    inclusionDecision: "include",
    exclusionReason: null,
    provenance: {
      recordedIn: "chef-gringo-repository",
      cataloguedAt: CATALOGUED_AT,
      notes: "Practice knowledge, not a live source check and not a retrieved document.",
    },
    overrideHistory: [],
    confidenceContribution: 0.7,
    productionExposure: true,
    topics: ["mirepoix", "aromatic base", "culinary technique"],
  },
  {
    id: "evidence:usda-fsis:ground-beef-160f",
    title: "USDA FSIS Safe Minimum Internal Temperature Chart",
    sourceOrganization: "USDA Food Safety and Inspection Service",
    sourceUrl: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/safe-temperature-chart",
    sourceType: "regulatory_document",
    authorityTier: 1,
    domain: "food_safety_public_health",
    publicationDate: null,
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: "USDA FSIS lists 160°F (71.1°C) as the safe minimum internal temperature for ground beef.",
    claimContradicted: null,
    excerpt: null,
    locator: "Safe Minimum Internal Temperature Chart — Ground Meat & Meat Mixtures, Beef",
    validationStatus: "claim_supporting",
    originalValidationStatus: "claim_supporting",
    freshnessStatus: "unknown",
    inclusionDecision: "include",
    exclusionReason: null,
    provenance: {
      recordedIn: "chef-gringo-repository",
      cataloguedAt: CATALOGUED_AT,
      notes: "Official FSIS chart URL already used as U.S. ground-beef guidance on the burger makeover page. Page body was not fetched in this environment; no quotation is stored.",
    },
    overrideHistory: [],
    confidenceContribution: 0.95,
    productionExposure: true,
    topics: ["ground beef", "safe temperature", "160f", "usda", "food safety"],
  },
  {
    id: "evidence:thermoworks:thermapen-one-response",
    title: "Thermapen ONE product specifications",
    sourceOrganization: "ThermoWorks",
    sourceUrl: "https://www.thermoworks.com/products/thermapen-one",
    sourceType: "manufacturer_documentation",
    authorityTier: 1,
    domain: "equipment",
    publicationDate: null,
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: "ThermoWorks states the Thermapen ONE response time as 1 second for this exact model.",
    claimContradicted: null,
    excerpt: "1 second",
    locator: "Marketplace catalog record thermoworks-thermapen-one, sourced from the manufacturer model page",
    validationStatus: "claim_supporting",
    originalValidationStatus: "claim_supporting",
    freshnessStatus: "unknown",
    inclusionDecision: "include",
    exclusionReason: null,
    provenance: {
      recordedIn: "chef-gringo-repository",
      cataloguedAt: CATALOGUED_AT,
      notes: "Exact-model specification copied from the existing Chef Gringo catalog source label, not from a new live fetch.",
    },
    overrideHistory: [],
    confidenceContribution: 0.85,
    productionExposure: true,
    topics: ["thermapen one", "thermoworks", "response time", "thermometer"],
  },
  {
    id: "evidence:florida-dbpr:hotels-restaurants",
    title: "Florida Division of Hotels and Restaurants",
    sourceOrganization: "Florida Department of Business and Professional Regulation",
    sourceUrl: "https://www.myfloridalicense.com/DBPR/hotels-restaurants/",
    sourceType: "statute_or_rule",
    authorityTier: 1,
    domain: "business_licensing",
    publicationDate: null,
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: "Florida public food service establishments are licensed through the Division of Hotels and Restaurants at the Department of Business and Professional Regulation.",
    claimContradicted: null,
    excerpt: null,
    locator: "Official DBPR Hotels and Restaurants landing page",
    validationStatus: "identified",
    originalValidationStatus: "identified",
    freshnessStatus: "unknown",
    inclusionDecision: "include",
    exclusionReason: null,
    provenance: {
      recordedIn: "chef-gringo-repository",
      cataloguedAt: CATALOGUED_AT,
      notes: "Agency identity is on file. Current statute text, fees, and county exceptions were not retrieved.",
    },
    overrideHistory: [],
    confidenceContribution: 0.6,
    productionExposure: true,
    topics: ["florida", "food license", "restaurant license", "dbpr", "cottage food"],
  },
];

export const TEST_ONLY_EVIDENCE: ResearchEvidenceItem[] = [
  {
    id: "evidence:test:conflict-a",
    title: "Synthetic CG-WIF-230 Installation Manual",
    sourceOrganization: "Example Refrigeration Co.",
    sourceUrl: "https://manufacturer.example.invalid/manuals/cg-wif-230",
    sourceType: "manufacturer_documentation",
    authorityTier: 1,
    domain: "equipment",
    publicationDate: null,
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: "Electrical requirement: 208-230V",
    claimContradicted: null,
    excerpt: "Electrical requirement: 208-230V",
    locator: "page 14",
    validationStatus: "claim_supporting",
    originalValidationStatus: "claim_supporting",
    freshnessStatus: "current",
    inclusionDecision: "include",
    exclusionReason: null,
    provenance: {
      recordedIn: "test_fixture",
      cataloguedAt: CATALOGUED_AT,
      notes: "Test-only .invalid fixture. Not production evidence.",
    },
    overrideHistory: [],
    confidenceContribution: 0.8,
    productionExposure: false,
    topics: ["cg-wif-230", "electrical", "conflict-demo"],
  },
  {
    id: "evidence:test:conflict-b",
    title: "Synthetic CG-WIF-230 Electrical Bulletin",
    sourceOrganization: "Example Refrigeration Co.",
    sourceUrl: "https://manufacturer.example.invalid/bulletins/cg-wif-230-electrical",
    sourceType: "manufacturer_documentation",
    authorityTier: 1,
    domain: "equipment",
    publicationDate: null,
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: "Electrical requirement: 460V",
    claimContradicted: "Electrical requirement: 208-230V",
    excerpt: "Electrical requirement: 460V",
    locator: "bulletin table 1",
    validationStatus: "contradicted",
    originalValidationStatus: "contradicted",
    freshnessStatus: "current",
    inclusionDecision: "include",
    exclusionReason: null,
    provenance: {
      recordedIn: "test_fixture",
      cataloguedAt: CATALOGUED_AT,
      notes: "Test-only conflicting counterpart. Not production evidence.",
    },
    overrideHistory: [],
    confidenceContribution: 0.8,
    productionExposure: false,
    topics: ["cg-wif-230", "electrical", "conflict-demo"],
  },
  {
    id: "evidence:test:stale-manual",
    title: "Synthetic withdrawn specification sheet",
    sourceOrganization: "Example Refrigeration Co.",
    sourceUrl: "https://manufacturer.example.invalid/manuals/cg-wif-230-2012",
    sourceType: "manufacturer_documentation",
    authorityTier: 2,
    domain: "equipment",
    publicationDate: "2012-01-01",
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: "Electrical requirement: 115V",
    claimContradicted: null,
    excerpt: "Electrical requirement: 115V",
    locator: "superseded sheet",
    validationStatus: "stale",
    originalValidationStatus: "stale",
    freshnessStatus: "stale",
    inclusionDecision: "exclude",
    exclusionReason: "Document is marked stale and is not current manufacturer guidance.",
    provenance: {
      recordedIn: "test_fixture",
      cataloguedAt: CATALOGUED_AT,
      notes: "Test-only stale fixture.",
    },
    overrideHistory: [],
    confidenceContribution: 0,
    productionExposure: false,
    topics: ["stale"],
  },
  {
    id: "evidence:test:rejected-seller",
    title: "Synthetic seller listing",
    sourceOrganization: "Example Marketplace Seller",
    sourceUrl: "https://seller.example.invalid/listings/cg-wif-control",
    sourceType: "seller_listing",
    authorityTier: 3,
    domain: "equipment",
    publicationDate: null,
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: "Seller claims this control fits CG-WIF-230",
    claimContradicted: null,
    excerpt: "Compatibility: seller claims this control fits CG-WIF-230",
    locator: "listing description",
    validationStatus: "rejected",
    originalValidationStatus: "rejected",
    freshnessStatus: "unknown",
    inclusionDecision: "lead_only",
    exclusionReason: "Seller listings cannot establish compatibility.",
    provenance: {
      recordedIn: "test_fixture",
      cataloguedAt: CATALOGUED_AT,
      notes: "Rejected internally; must not appear in public answers.",
    },
    overrideHistory: [],
    confidenceContribution: 0,
    productionExposure: false,
    topics: ["seller", "rejected-demo"],
  },
  {
    id: "evidence:test:url-only",
    title: "URL without a supported claim",
    sourceOrganization: "Unknown",
    sourceUrl: "https://example.invalid/bare-link",
    sourceType: "seller_listing",
    authorityTier: 3,
    domain: "commercial_claims",
    publicationDate: null,
    updateDate: null,
    retrievedAt: null,
    cataloguedAt: CATALOGUED_AT,
    claimSupported: null,
    claimContradicted: null,
    excerpt: null,
    locator: null,
    validationStatus: "submitted",
    originalValidationStatus: "submitted",
    freshnessStatus: "unknown",
    inclusionDecision: "exclude",
    exclusionReason: "A URL alone is not supporting evidence.",
    provenance: {
      recordedIn: "test_fixture",
      cataloguedAt: CATALOGUED_AT,
      notes: "Negative fixture for URL-only rejection.",
    },
    overrideHistory: [],
    confidenceContribution: 0,
    productionExposure: false,
    topics: ["url-only"],
  },
];
