import {claimDispatchAttempt,recordDispatchTransportResult,signDispatchEnvelope,type DispatchTransportResult} from "../../../../../db/growth-os-dispatcher.ts";
import {growthDb,growthError,requireGrowthAdministrator} from "../../_shared.ts";

export const dynamic="force-dynamic";

type RuntimeEnv={GROWTH_DISPATCH_ENDPOINT?:string;GROWTH_DISPATCH_SECRET?:string;GROWTH_DISPATCH_ADAPTER?:string};
function config(){const runtime=(globalThis as typeof globalThis&{__CHEF_GRINGO_ENV__?:RuntimeEnv}).__CHEF_GRINGO_ENV__;return {endpoint:runtime?.GROWTH_DISPATCH_ENDPOINT??process.env.GROWTH_DISPATCH_ENDPOINT??"",secret:runtime?.GROWTH_DISPATCH_SECRET??process.env.GROWTH_DISPATCH_SECRET??"",adapter:runtime?.GROWTH_DISPATCH_ADAPTER??process.env.GROWTH_DISPATCH_ADAPTER??"unconfigured"};}
function resultFromResponse(response:Response,payload:Record<string,unknown>|null):DispatchTransportResult{const remotePublicationId=typeof payload?.remotePublicationId==="string"?payload.remotePublicationId:null;const remotePublicationUrl=typeof payload?.remotePublicationUrl==="string"?payload.remotePublicationUrl:null;if(response.ok)return {status:"accepted",responseCode:response.status,remotePublicationId,remotePublicationUrl};if(response.status>=400&&response.status<500)return {status:"failed",responseCode:response.status,error:`Dispatcher rejected the request with HTTP ${response.status}.`};return {status:"ambiguous",responseCode:response.status,remotePublicationId,remotePublicationUrl,error:`Dispatcher returned HTTP ${response.status}; remote publication state is uncertain.`};}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){const {administrator,response}=requireGrowthAdministrator(request);if(response||!administrator)return response;try{const {endpoint,secret,adapter}=config();if(!endpoint||!secret)return Response.json({error:"Dispatcher transport is not configured. Set both GROWTH_DISPATCH_ENDPOINT and GROWTH_DISPATCH_SECRET before attempting outbound delivery."},{status:503});const parsed=new URL(endpoint);if(parsed.protocol!=="https:")return Response.json({error:"Dispatcher endpoint must use HTTPS."},{status:503});const {id}=await context.params;const claim=await claimDispatchAttempt(growthDb(),{outboxId:decodeURIComponent(id),adapter});const signed=await signDispatchEnvelope(claim.envelope,secret);let transport:DispatchTransportResult;try{const outbound=await fetch(parsed,{method:"POST",headers:{"content-type":"application/json","x-chef-gringo-signature":signed.signature,"x-chef-gringo-idempotency-key":claim.envelope.idempotencyKey,"x-chef-gringo-lease-token":claim.leaseToken},body:signed.body,redirect:"error"});let payload:Record<string,unknown>|null=null;try{payload=await outbound.json() as Record<string,unknown>}catch{payload=null}transport=resultFromResponse(outbound,payload);}catch(error){transport={status:"ambiguous",error:error instanceof Error?`Dispatcher transport error: ${error.message}`:"Dispatcher transport failed with unknown remote state."};}const entry=await recordDispatchTransportResult(growthDb(),{outboxId:claim.envelope.outboxId,leaseToken:claim.leaseToken,result:transport});return Response.json({entry,transport:{status:transport.status,responseCode:transport.responseCode??null},verificationRequired:entry.state==="published_unverified"});}catch(error){return growthError(error)}}
