import type { PartnerHuntRecord } from "./partner-hunt";

const thermoworksEvidence: PartnerHuntRecord["evidence"] = [
  {
    id: "partner-evidence:thermoworks:identity",
    sourceUrl: "https://www.thermoworks.com/pages/affiliate",
    sourceType: "provider_terms",
    retrievedAt: "2026-08-13",
    claimType: "company_identity",
    claim: "ThermoWorks operates the official ThermoWorks website and publishes an affiliate-program page for its products.",
    confidence: "high",
    verificationState: "verified",
    notes: "Official ThermoWorks affiliate page.",
    contradiction: false,
  },
  {
    id: "partner-evidence:thermoworks:program",
    sourceUrl: "https://affiliates.thermoworks.com/",
    sourceType: "provider_terms",
    retrievedAt: "2026-08-13",
    claimType: "program_exists",
    claim: "ThermoWorks currently operates a public affiliate program with an application path.",
    confidence: "high",
    verificationState: "verified",
    notes: "Official ThermoWorks affiliate-program site.",
    contradiction: false,
  },
  {
    id: "partner-evidence:thermoworks:payout",
    sourceUrl: "https://affiliates.thermoworks.com/affiliates/faq.php",
    sourceType: "provider_terms",
    retrievedAt: "2026-08-13",
    claimType: "payout",
    claim: "ThermoWorks states affiliates earn 10% of qualifying sale value.",
    confidence: "high",
    verificationState: "verified",
    notes: "Official affiliate FAQ. Payment thresholds vary by payout method, so no single threshold is asserted in economics.",
    contradiction: false,
  },
  {
    id: "partner-evidence:thermoworks:attribution",
    sourceUrl: "https://affiliates.thermoworks.com/affiliates/faq.php",
    sourceType: "provider_terms",
    retrievedAt: "2026-08-13",
    claimType: "attribution",
    claim: "ThermoWorks states qualifying purchases can receive referral credit for up to 30 days after the initial click-through.",
    confidence: "high",
    verificationState: "verified",
    notes: "Official affiliate FAQ.",
    contradiction: false,
  },
  {
    id: "partner-evidence:thermoworks:terms",
    sourceUrl: "https://affiliates.thermoworks.com/affiliates/faq.php",
    sourceType: "provider_terms",
    retrievedAt: "2026-08-13",
    claimType: "current_terms",
    claim: "ThermoWorks publishes current affiliate qualification, payment, tracking, and website requirements through its official affiliate FAQ.",
    confidence: "moderate",
    verificationState: "verified",
    notes: "A full restriction review is still required before application readiness.",
    contradiction: false,
  },
];

export const thermoworksCandidate: PartnerHuntRecord = {
  id: "partner:thermoworks:affiliate",
  providerName: "ThermoWorks",
  website: "https://www.thermoworks.com/",
  commercialLane: "equipment_supplies",
  programType: "affiliate",
  regionsServed: "United States; other eligibility not yet verified",
  usAvailability: true,
  description: "Temperature tools for professional kitchens, food safety, cooking, refrigeration monitoring, and related workflows.",
  whyItMatters: "Chef Gringo already has publication-ready ThermoWorks products in temperature-control workflows, so the commercial relationship would monetize existing operator value rather than create a recommendation for commission.",
  customerValueThesis: "Thermapen ONE, ThermoPop 2, and ChefAlarm already map to distinct operator temperature-control jobs with strong first-party product evidence.",
  contactOrApplicationRoute: "https://affiliates.thermoworks.com/",
  proposedRelationship: "affiliate",
  majorRestrictionsUnderstood: false,
  credibilityBlockers: [],
  economics: {
    oneTimePayoutCents: null,
    recurringPayoutCents: null,
    revenueSharePercent: 10,
    residualStructure: null,
    qualifiedLeadPayoutCents: null,
    salePayoutCents: null,
    attributionWindowDays: 30,
    payoutTimingDays: null,
    payoutThresholdCents: null,
    clawbackRules: null,
  },
  evidence: thermoworksEvidence,
  verification: {
    identityVerified: true,
    programExists: true,
    currentTermsVerified: true,
    usEligibilityVerified: false,
    payoutVerified: true,
    attributionVerified: true,
    restrictionsVerified: false,
    customerValueReviewed: false,
  },
  lifecycle: "needs_verification",
  rejectedReason: null,
  synthetic: false,
};

export const researchedPartnerCandidates: PartnerHuntRecord[] = [thermoworksCandidate];
