import type { CommercialLane, PartnerEconomics } from "./types";

export const PARTNER_LIFECYCLE_STATES=["discovered","researching","needs_verification","ready_to_apply","application_submitted","approved","rejected","needs_outreach","outreach_planned","negotiating","active","paused","expired"] as const;
export type PartnerLifecycleState=typeof PARTNER_LIFECYCLE_STATES[number];
export const PROGRAM_RELATIONSHIP_TYPES=["affiliate","referral","reseller","dealer","qualified_lead","recurring_commission","residual","revenue_share","wholesale","performance_marketing","manufacturer_direct","oem_private_label","direct_outreach"] as const;
export type ProgramRelationshipType=typeof PROGRAM_RELATIONSHIP_TYPES[number];
export type VerificationChecklist={identityVerified:boolean;programExists:boolean;currentTermsVerified:boolean;usEligibilityVerified:boolean;payoutVerified:boolean;attributionVerified:boolean;restrictionsVerified:boolean;customerValueReviewed:boolean};
export type PartnerEvidence={id:string;sourceUrl:string;sourceType:"provider_terms"|"network_listing"|"application_page"|"correspondence"|"editorial_note";retrievedAt:string;claim:string;confidence:"insufficient"|"low"|"moderate"|"high";verificationState:"unverified"|"verified"|"disputed";notes:string;contradiction:boolean};
export type PartnerHuntRecord={id:string;providerName:string;website:string;commercialLane:CommercialLane;programType:ProgramRelationshipType;regionsServed:string;usAvailability:boolean|null;description:string;whyItMatters:string;customerValueThesis:string;contactOrApplicationRoute:string|null;proposedRelationship:ProgramRelationshipType|null;majorRestrictionsUnderstood:boolean;credibilityBlockers:string[];economics:PartnerEconomics;evidence:PartnerEvidence[];verification:VerificationChecklist;lifecycle:PartnerLifecycleState;rejectedReason:string|null;synthetic:boolean};

const transitions:Record<PartnerLifecycleState,readonly PartnerLifecycleState[]>={discovered:["researching","needs_outreach","rejected"],researching:["needs_verification","ready_to_apply","needs_outreach","rejected"],needs_verification:["researching","ready_to_apply","needs_outreach","rejected"],ready_to_apply:["application_submitted","needs_verification"],application_submitted:["approved","rejected"],approved:["active","paused"],rejected:["researching"],needs_outreach:["outreach_planned","researching","rejected"],outreach_planned:["negotiating","paused"],negotiating:["active","paused","rejected"],active:["paused","expired"],paused:["active","expired"],expired:["researching"]};
export function transitionPartner(record:PartnerHuntRecord,next:PartnerLifecycleState){if(!transitions[record.lifecycle].includes(next))throw new Error(`Invalid partner lifecycle transition: ${record.lifecycle} → ${next}`);return {...record,lifecycle:next};}
export function verificationFailures(record:PartnerHuntRecord){const failures:string[]=[];const v=record.verification;if(!v.identityVerified)failures.push("Company identity is not verified");if(record.evidence.length===0)failures.push("No evidence is attached");if(record.evidence.some(item=>item.contradiction))failures.push("Evidence contains an unresolved contradiction");if(record.lifecycle==="active"&&(!v.programExists||!v.currentTermsVerified||!v.usEligibilityVerified||!v.payoutVerified||!v.attributionVerified||!v.restrictionsVerified||!v.customerValueReviewed))failures.push("Active status requires every verification check");return failures;}
export function readiness(record:PartnerHuntRecord,kind:"apply"|"outreach"){const missing:string[]=[];if(!record.verification.identityVerified)missing.push("Resolve company identity");if(!record.customerValueThesis.trim())missing.push("Write the customer-value thesis");if(!record.evidence.length)missing.push("Attach evidence");if(!record.contactOrApplicationRoute)missing.push(kind==="apply"?"Record the application route":"Record a contact route");if(!record.proposedRelationship)missing.push("Choose a proposed commercial relationship");if(!record.majorRestrictionsUnderstood)missing.push("Review major restrictions");if(record.credibilityBlockers.length)missing.push("Resolve credibility blockers");if(kind==="apply"&&!record.verification.programExists)missing.push("Verify that the program exists");return {ready:missing.length===0,missing};}
export function canAppearVerified(record:PartnerHuntRecord){return verificationFailures(record).length===0&&record.evidence.some(item=>item.verificationState==="verified")&&record.verification.currentTermsVerified;}
