import type { EvidenceClaim, IntelligenceConfidence, PartnerProgramType } from "../marketplace/intelligence/types";

export const COMMERCIAL_LANES = ["unknown","equipment_supplies","factory_direct","pos_payments","software","services","business_capital","growth_customer_acquisition"] as const;
export type CommercialLane = typeof COMMERCIAL_LANES[number];
export const GROWTH_CAPABILITIES = ["customer_acquisition","campaign_creation","local_advertising","paid_search","social_advertising","email_marketing","sms_marketing","seo_content","landing_pages","offer_development","creative_production","reputation_reviews","loyalty","retention","remarketing","referral_programs","lead_generation","conversion_tracking","campaign_optimization"] as const;
export type GrowthCapability = typeof GROWTH_CAPABILITIES[number];

export type PartnerEconomics = { oneTimePayoutCents:number|null; recurringPayoutCents:number|null; revenueSharePercent:number|null; residualStructure:string|null; qualifiedLeadPayoutCents:number|null; salePayoutCents:number|null; attributionWindowDays:number|null; payoutTimingDays:number|null; payoutThresholdCents:number|null; clawbackRules:string|null };
export type PartnerOpportunity = { id:string; providerName:string; programName:string; programType:PartnerProgramType|"reseller"|"dealer"|"revenue_share"|"qualified_lead"|"performance_marketing"; commercialLane:CommercialLane; countriesServed:string[]; usAvailability:boolean|null; customerSegments:string[]; economics:PartnerEconomics; conversionRequirements:string|null; applicationRequirements:string|null; restrictions:{paidSearch:string|null; directLinking:string|null; brandBidding:string|null}; apiOrFeedAvailable:boolean|null; trackingMethod:string|null; customerDiscount:string|null; commercialTermsSource:string|null; termsLastVerified:string|null; evidence:EvidenceClaim[]; confidence:IntelligenceConfidence; relationshipStatus:"needs_research"|"needs_application"|"needs_outreach"|"negotiation_opportunity"|"verified"|"rejected" };

export type CustomerValueComponents = { operatorFit:number; totalCost:number; quality:number; support:number; warranty:number; switchingCost:number; contractBurden:number; reliability:number; evidence:number; expectedOperatorValue:number };
export type CommercialOpportunityComponentsV2 = { payout:number|null; recurringRevenue:number|null; revenueShare:number|null; expectedConversion:number|null; approvalProbability:number|null; attributionQuality:number|null; payoutTiming:number|null; reversalRisk:number|null; expectedLifetimeRevenue:number|null };
export type CustomerValueScorecard = { opportunityId:string; components:CustomerValueComponents; score:number };
export type CommercialOpportunityScorecardV2 = { opportunityId:string; components:CommercialOpportunityComponentsV2; score:number|null };
export type ExpectedCommercialValueInput = { payoutCents:number|null; conversionProbability:number|null; approvalProbability:number|null; retentionMultiplier:number|null; acquisitionCostCents:number|null };

export type DemandSignal = { problem:string; categoryInterest:string|null; geographicMarket:string|null; urgency:"unknown"|"planning"|"soon"|"urgent"; budgetCents:number|null; businessType:string|null; intent:"opening"|"replacement"|"repair"|"switching_provider"|"customer_acquisition"|"unknown" };
export type FounderMetrics = { visitors:number|null; problemsAnalyzed:number|null; productViews:number|null; merchantClicks:number|null; qualifiedLeads:number|null; sales:number|null; pendingCommissionCents:number|null; approvedCommissionCents:number|null; paidCommissionCents:number|null; recurringRevenueCents:number|null; advertisingSpendCents:number|null; costPerLeadCents:number|null; costPerAcquisitionCents:number|null; revenuePerVisitorCents:number|null; earningsPerClickCents:number|null; roas:number|null; profitCents:number|null; verifiedCustomerSavingsCents:number|null };
